INSERT INTO api_versions (api_name_version, api_version, product_feature, stage_name_version)
VALUES
  ('Dados Abertos - Fase 1', '1.0.0-beta.1', 'Adiantamento a Depositantes', 'Dados Abertos - Fase 1 - Adiantamento a Depositantes'),
  ('Dados Abertos - Fase 1', '1.0.0', 'Adiantamento a Depositantes', 'Dados Abertos - Fase 1 - Adiantamento a Depositantes'),
  ('Dados Abertos - Fase 1', 'Não se Aplica', 'Adiantamento a Depositantes', 'Dados Abertos - Fase 1 - Adiantamento a Depositantes'),
  ('Dados Abertos - Fase 1', '1.0.0-beta.2', 'Adiantamento a Depositantes', 'Dados Abertos - Fase 1 - Adiantamento a Depositantes'),
  ('Dados Abertos - Fase 1', '1.1.0', 'Adiantamento a Depositantes', 'Dados Abertos - Fase 1 - Adiantamento a Depositantes'),
  ('Dados Abertos - Fase 1', '1.2.0', 'Adiantamento a Depositantes', 'Dados Abertos - Fase 1 - Adiantamento a Depositantes'),
  ('Dados Abertos - Fase 1', '1.0.1', 'Adiantamento a Depositantes', 'Dados Abertos - Fase 1 - Adiantamento a Depositantes'),
  ('Dados Abertos - Fase 1', '1.0.0-beta.1', 'Adiantamento de Recebíveis', 'Dados Abertos - Fase 1 - Adiantamento de Recebíveis'),
  ('Dados Abertos - Fase 1', '1.0.0', 'Adiantamento de Recebíveis', 'Dados Abertos - Fase 1 - Adiantamento de Recebíveis'),
  ('Dados Abertos - Fase 1', 'Não se Aplica', 'Adiantamento de Recebíveis', 'Dados Abertos - Fase 1 - Adiantamento de Recebíveis'),
  ('Dados Abertos - Fase 1', '1.0.2', 'Canais de Atendimento', 'Dados Abertos - Fase 1 - Canais de Atendimento'),
  ('Dados Abertos - Fase 1', 'Não se Aplica', 'Canais de Atendimento', 'Dados Abertos - Fase 1 - Canais de Atendimento'),
  ('Dados Abertos - Fase 1', '1.0.0-beta.1', 'Canais de Atendimento', 'Dados Abertos - Fase 1 - Canais de Atendimento'),
  ('Dados Abertos - Fase 1', '2.0.0-beta.1', 'Canais de Atendimento', 'Dados Abertos - Fase 1 - Canais de Atendimento'),
  ('Dados Abertos - Fase 1', '2.0.0', 'Canais de Atendimento', 'Dados Abertos - Fase 1 - Canais de Atendimento'),
  ('Dados Abertos - Fase 1', '2.0.1', 'Canais de Atendimento', 'Dados Abertos - Fase 1 - Canais de Atendimento'),
  ('Dados Abertos - Fase 1', '1.0.0-beta.1', 'Cartão de Crédito', 'Dados Abertos - Fase 1 - Cartão de Crédito'),
  ('Dados Abertos - Fase 1', '1.0.0', 'Cartão de Crédito', 'Dados Abertos - Fase 1 - Cartão de Crédito'),
  ('Dados Abertos - Fase 1', 'Não se Aplica', 'Cartão de Crédito', 'Dados Abertos - Fase 1 - Cartão de Crédito'),
  ('Dados Abertos - Fase 1', '1.0.0-beta.2', 'Cartão de Crédito', 'Dados Abertos - Fase 1 - Cartão de Crédito'),
  ('Dados Abertos - Fase 1', '1.0.1', 'Cartão de Crédito', 'Dados Abertos - Fase 1 - Cartão de Crédito'),
  ('Dados Abertos - Fase 1', '1.0.0-beta.1', 'Contas', 'Dados Abertos - Fase 1 - Contas'),
  ('Dados Abertos - Fase 1', 'Não se Aplica', 'Contas', 'Dados Abertos - Fase 1 - Contas'),
  ('Dados Abertos - Fase 1', '1.0.0', 'Contas', 'Dados Abertos - Fase 1 - Contas'),
  ('Dados Abertos - Fase 1', '1.0.0-beta.2', 'Contas', 'Dados Abertos - Fase 1 - Contas'),
  ('Dados Abertos - Fase 1', '1.0.1', 'Contas', 'Dados Abertos - Fase 1 - Contas'),
  ('Dados Abertos - Fase 1', '1.0.0-beta.2', 'Direitos Creditórios Descontados', 'Dados Abertos - Fase 1 - Direitos Creditórios Descontados'),
  ('Dados Abertos - Fase 1', 'Não se Aplica', 'Direitos Creditórios Descontados', 'Dados Abertos - Fase 1 - Direitos Creditórios Descontados'),
  ('Dados Abertos - Fase 1', '1.0.0', 'Direitos Creditórios Descontados', 'Dados Abertos - Fase 1 - Direitos Creditórios Descontados'),
  ('Dados Abertos - Fase 1', '1.0.1', 'Direitos Creditórios Descontados', 'Dados Abertos - Fase 1 - Direitos Creditórios Descontados'),
  ('Dados Abertos - Fase 1', '1.0.0-beta.1', 'Empréstimos', 'Dados Abertos - Fase 1 - Empréstimos'),
  ('Dados Abertos - Fase 1', '1.0.0', 'Empréstimos', 'Dados Abertos - Fase 1 - Empréstimos'),
  ('Dados Abertos - Fase 1', 'Não se Aplica', 'Empréstimos', 'Dados Abertos - Fase 1 - Empréstimos'),
  ('Dados Abertos - Fase 1', '1.0.0-beta.2', 'Empréstimos', 'Dados Abertos - Fase 1 - Empréstimos'),
  ('Dados Abertos - Fase 1', '1.0.1', 'Empréstimos', 'Dados Abertos - Fase 1 - Empréstimos'),
  ('Dados Abertos - Fase 1', '1.0.0-beta.1', 'Financiamentos', 'Dados Abertos - Fase 1 - Financiamentos'),
  ('Dados Abertos - Fase 1', '1.0.0', 'Financiamentos', 'Dados Abertos - Fase 1 - Financiamentos'),
  ('Dados Abertos - Fase 1', 'Não se Aplica', 'Financiamentos', 'Dados Abertos - Fase 1 - Financiamentos'),
  ('Dados Abertos - Fase 1', '1.0.0-beta.2', 'Financiamentos', 'Dados Abertos - Fase 1 - Financiamentos'),
  ('Dados Abertos - Fase 1', '1.0.1', 'Financiamentos', 'Dados Abertos - Fase 1 - Financiamentos'),
  ('Dados Abertos - Fase 1', '1.0.2', 'Produtos e Serviços', 'Dados Abertos - Fase 1 - Produtos e Serviços'),
  ('Dados Abertos - Fase 1', 'Não se Aplica', 'Produtos e Serviços', 'Dados Abertos - Fase 1 - Produtos e Serviços'),
  ('Dados Abertos - Fase 4A', '1.0.0', 'Câmbio', 'Dados Abertos - Fase 4A - Câmbio'),
  ('Dados Abertos - Fase 4A', 'Não se Aplica', 'Câmbio', 'Dados Abertos - Fase 4A - Câmbio'),
  ('Dados Abertos - Fase 4A', '1.0.1', 'Câmbio', 'Dados Abertos - Fase 4A - Câmbio'),
  ('Dados Abertos - Fase 4A', '1.0.0', 'Credenciamento', 'Dados Abertos - Fase 4A - Credenciamento'),
  ('Dados Abertos - Fase 4A', 'Não se Aplica', 'Credenciamento', 'Dados Abertos - Fase 4A - Credenciamento'),
  ('Dados Abertos - Fase 4A', '1.0.1', 'Credenciamento', 'Dados Abertos - Fase 4A - Credenciamento'),
  ('Dados Abertos - Fase 4A', '1.0.0', 'Investimentos', 'Dados Abertos - Fase 4A - Investimentos'),
  ('Dados Abertos - Fase 4A', 'Não se Aplica', 'Investimentos', 'Dados Abertos - Fase 4A - Investimentos'),
  ('Dados Abertos - Fase 4A', '1.0.1', 'Investimentos', 'Dados Abertos - Fase 4A - Investimentos'),
  ('Dados Abertos - Fase 4A', '1.0.0-rc1.0', 'Previdência', 'Dados Abertos - Fase 4A - Previdência'),
  ('Dados Abertos - Fase 4A', 'Não se Aplica', 'Previdência', 'Dados Abertos - Fase 4A - Previdência'),
  ('Dados Abertos - Fase 4A', '1.0.0-rc2.0', 'Previdência', 'Dados Abertos - Fase 4A - Previdência'),
  ('Dados Abertos - Fase 4A', '1.0.0', 'Previdência', 'Dados Abertos - Fase 4A - Previdência'),
  ('Dados Abertos - Fase 4A', '1.0.1', 'Previdência', 'Dados Abertos - Fase 4A - Previdência'),
  ('Dados Abertos - Fase 4A', '2.0.0-beta.1', 'Previdência', 'Dados Abertos - Fase 4A - Previdência'),
  ('Dados Abertos - Fase 4A', '2.0.0', 'Previdência', 'Dados Abertos - Fase 4A - Previdência'),
  ('Dados Abertos - Fase 4A', '1.0.0-rc1.0', 'Seguros', 'Dados Abertos - Fase 4A - Seguros'),
  ('Dados Abertos - Fase 4A', 'Não se Aplica', 'Seguros', 'Dados Abertos - Fase 4A - Seguros'),
  ('Dados Abertos - Fase 4A', '1.0.0-rc2.0', 'Seguros', 'Dados Abertos - Fase 4A - Seguros'),
  ('Dados Abertos - Fase 4A', '1.0.0', 'Seguros', 'Dados Abertos - Fase 4A - Seguros'),
  ('Dados Abertos - Fase 4A', '1.0.1', 'Seguros', 'Dados Abertos - Fase 4A - Seguros'),
  ('Dados Abertos - Fase 4A', '2.0.0-beta.1', 'Seguros', 'Dados Abertos - Fase 4A - Seguros'),
  ('Dados Abertos - Fase 4A', '2.0.0', 'Seguros', 'Dados Abertos - Fase 4A - Seguros'),
  ('Dados Abertos - Fase 4A', '1.0.0-rc2.0', 'Títulos de Capitalização', 'Dados Abertos - Fase 4A - Títulos de Capitalização'),
  ('Dados Abertos - Fase 4A', 'Não se Aplica', 'Títulos de Capitalização', 'Dados Abertos - Fase 4A - Títulos de Capitalização'),
  ('Dados Abertos - Fase 4A', '1.0.0-rc1.0', 'Títulos de Capitalização', 'Dados Abertos - Fase 4A - Títulos de Capitalização'),
  ('Dados Abertos - Fase 4A', '1.0.0', 'Títulos de Capitalização', 'Dados Abertos - Fase 4A - Títulos de Capitalização'),
  ('Dados Abertos - Fase 4A', '1.0.1', 'Títulos de Capitalização', 'Dados Abertos - Fase 4A - Títulos de Capitalização'),
  ('Dados Abertos - Fase 4A', '2.0.0-beta.1', 'Títulos de Capitalização', 'Dados Abertos - Fase 4A - Títulos de Capitalização'),
  ('Dados Abertos - Fase 4A', '2.0.0', 'Títulos de Capitalização', 'Dados Abertos - Fase 4A - Títulos de Capitalização'),
  ('Dados Cliente - Fase 2', '2.0.1', 'Cartão de Crédito', 'Dados Cliente - Fase 2 - Cartão de Crédito'),
  ('Dados Cliente - Fase 2', '1.0.4', 'Cartão de Crédito', 'Dados Cliente - Fase 2 - Cartão de Crédito'),
  ('Dados Cliente - Fase 2', 'Não se Aplica', 'Cartão de Crédito', 'Dados Cliente - Fase 2 - Cartão de Crédito'),
  ('Dados Cliente - Fase 2', '2.1.0-rc.1', 'Cartão de Crédito', 'Dados Cliente - Fase 2 - Cartão de Crédito'),
  ('Dados Cliente - Fase 2', '2.1.0', 'Cartão de Crédito', 'Dados Cliente - Fase 2 - Cartão de Crédito'),
  ('Dados Cliente - Fase 2', '2.1.0-rc.2', 'Cartão de Crédito', 'Dados Cliente - Fase 2 - Cartão de Crédito'),
  ('Dados Cliente - Fase 2', '2.2.0', 'Cartão de Crédito', 'Dados Cliente - Fase 2 - Cartão de Crédito'),
  ('Dados Cliente - Fase 2', '2.2.1', 'Cartão de Crédito', 'Dados Cliente - Fase 2 - Cartão de Crédito'),
  ('Dados Cliente - Fase 2', '2.3.1', 'Cartão de Crédito', 'Dados Cliente - Fase 2 - Cartão de Crédito'),
  ('Dados Cliente - Fase 2', '2.4.0', 'Cartão de Crédito', 'Dados Cliente - Fase 2 - Cartão de Crédito'),
  ('Dados Cliente - Fase 2', '2.3.0', 'Cartão de Crédito', 'Dados Cliente - Fase 2 - Cartão de Crédito'),
  ('Dados Cliente - Fase 2', '2.0.1', 'Consentimento', 'Dados Cliente - Fase 2 - Consentimento'),
  ('Dados Cliente - Fase 2', '1.0.3', 'Consentimento', 'Dados Cliente - Fase 2 - Consentimento'),
  ('Dados Cliente - Fase 2', 'Não se Aplica', 'Consentimento', 'Dados Cliente - Fase 2 - Consentimento'),
  ('Dados Cliente - Fase 2', '2.1.0', 'Consentimento', 'Dados Cliente - Fase 2 - Consentimento'),
  ('Dados Cliente - Fase 2', '2.2.0-beta.1', 'Consentimento', 'Dados Cliente - Fase 2 - Consentimento'),
  ('Dados Cliente - Fase 2', '2.2.0', 'Consentimento', 'Dados Cliente - Fase 2 - Consentimento'),
  ('Dados Cliente - Fase 2', '3.0.0-beta.1', 'Consentimento', 'Dados Cliente - Fase 2 - Consentimento'),
  ('Dados Cliente - Fase 2', '2.1.0-rc2.0', 'Consentimento', 'Dados Cliente - Fase 2 - Consentimento'),
  ('Dados Cliente - Fase 2', '3.0.0-beta.2', 'Consentimento', 'Dados Cliente - Fase 2 - Consentimento'),
  ('Dados Cliente - Fase 2', '3.0.0-rc.1', 'Consentimento', 'Dados Cliente - Fase 2 - Consentimento'),
  ('Dados Cliente - Fase 2', '3.0.0', 'Consentimento', 'Dados Cliente - Fase 2 - Consentimento'),
  ('Dados Cliente - Fase 2', '3.0.1', 'Consentimento', 'Dados Cliente - Fase 2 - Consentimento'),
  ('Dados Cliente - Fase 2', '3.1.0', 'Consentimento', 'Dados Cliente - Fase 2 - Consentimento'),
  ('Dados Cliente - Fase 2', '3.2.0', 'Consentimento', 'Dados Cliente - Fase 2 - Consentimento'),
  ('Dados Cliente - Fase 2', '3.3.0', 'Consentimento', 'Dados Cliente - Fase 2 - Consentimento'),
  ('Dados Cliente - Fase 2', '3.3.1', 'Consentimento', 'Dados Cliente - Fase 2 - Consentimento'),
  ('Dados Cliente - Fase 2', '2.0.1', 'Contas', 'Dados Cliente - Fase 2 - Contas'),
  ('Dados Cliente - Fase 2', '1.0.3', 'Contas', 'Dados Cliente - Fase 2 - Contas'),
  ('Dados Cliente - Fase 2', 'Não se Aplica', 'Contas', 'Dados Cliente - Fase 2 - Contas'),
  ('Dados Cliente - Fase 2', '2.1.0-rc.1', 'Contas', 'Dados Cliente - Fase 2 - Contas'),
  ('Dados Cliente - Fase 2', '2.1.0', 'Contas', 'Dados Cliente - Fase 2 - Contas'),
  ('Dados Cliente - Fase 2', '2.1.0-rc.2', 'Contas', 'Dados Cliente - Fase 2 - Contas'),
  ('Dados Cliente - Fase 2', '2.2.0', 'Contas', 'Dados Cliente - Fase 2 - Contas'),
  ('Dados Cliente - Fase 2', '2.2.1', 'Contas', 'Dados Cliente - Fase 2 - Contas'),
  ('Dados Cliente - Fase 2', '2.3.0', 'Contas', 'Dados Cliente - Fase 2 - Contas'),
  ('Dados Cliente - Fase 2', '2.4.0-beta.1', 'Contas', 'Dados Cliente - Fase 2 - Contas'),
  ('Dados Cliente - Fase 2', '2.4.0', 'Contas', 'Dados Cliente - Fase 2 - Contas'),
  ('Dados Cliente - Fase 2', '2.4.1', 'Contas', 'Dados Cliente - Fase 2 - Contas'),
  ('Dados Cliente - Fase 2', '2.5.0-beta.1', 'Contas', 'Dados Cliente - Fase 2 - Contas'),
  ('Dados Cliente - Fase 2', '2.5.0', 'Contas', 'Dados Cliente - Fase 2 - Contas'),
  ('Dados Cliente - Fase 2', '2.4.2', 'Contas', 'Dados Cliente - Fase 2 - Contas'),
  ('Dados Cliente - Fase 2', '2.0.1', 'Dados Cadastrais', 'Dados Cliente - Fase 2 - Dados Cadastrais'),
  ('Dados Cliente - Fase 2', '1.0.3', 'Dados Cadastrais', 'Dados Cliente - Fase 2 - Dados Cadastrais'),
  ('Dados Cliente - Fase 2', 'Não se Aplica', 'Dados Cadastrais', 'Dados Cliente - Fase 2 - Dados Cadastrais'),
  ('Dados Cliente - Fase 2', '2.1.0-beta.2', 'Dados Cadastrais', 'Dados Cliente - Fase 2 - Dados Cadastrais'),
  ('Dados Cliente - Fase 2', '2.1.0-beta.3', 'Dados Cadastrais', 'Dados Cliente - Fase 2 - Dados Cadastrais'),
  ('Dados Cliente - Fase 2', '2.1.0-rc.2', 'Dados Cadastrais', 'Dados Cliente - Fase 2 - Dados Cadastrais'),
  ('Dados Cliente - Fase 2', '2.1.0', 'Dados Cadastrais', 'Dados Cliente - Fase 2 - Dados Cadastrais'),
  ('Dados Cliente - Fase 2', '2.2.0', 'Dados Cadastrais', 'Dados Cliente - Fase 2 - Dados Cadastrais'),
  ('Dados Cliente - Fase 2', '2.2.1', 'Dados Cadastrais', 'Dados Cliente - Fase 2 - Dados Cadastrais'),
  ('Dados Cliente - Fase 2', '2.3.0', 'Dados Cadastrais', 'Dados Cliente - Fase 2 - Dados Cadastrais'),
  ('Dados Cliente - Fase 2', '2.0.1', 'Op. Cr. Direito Creditório Descontado', 'Dados Cliente - Fase 2 - Op. Cr. Direito Creditório Descontado'),
  ('Dados Cliente - Fase 2', '1.0.4', 'Op. Cr. Direito Creditório Descontado', 'Dados Cliente - Fase 2 - Op. Cr. Direito Creditório Descontado'),
  ('Dados Cliente - Fase 2', 'Não se Aplica', 'Op. Cr. Direito Creditório Descontado', 'Dados Cliente - Fase 2 - Op. Cr. Direito Creditório Descontado'),
  ('Dados Cliente - Fase 2', '2.1.0', 'Op. Cr. Direito Creditório Descontado', 'Dados Cliente - Fase 2 - Op. Cr. Direito Creditório Descontado'),
  ('Dados Cliente - Fase 2', '2.1.0-rc.1', 'Op. Cr. Direito Creditório Descontado', 'Dados Cliente - Fase 2 - Op. Cr. Direito Creditório Descontado'),
  ('Dados Cliente - Fase 2', '2.2.0', 'Op. Cr. Direito Creditório Descontado', 'Dados Cliente - Fase 2 - Op. Cr. Direito Creditório Descontado'),
  ('Dados Cliente - Fase 2', '2.3.0', 'Op. Cr. Direito Creditório Descontado', 'Dados Cliente - Fase 2 - Op. Cr. Direito Creditório Descontado'),
  ('Dados Cliente - Fase 2', '2.4.0-beta.1', 'Op. Cr. Direito Creditório Descontado', 'Dados Cliente - Fase 2 - Op. Cr. Direito Creditório Descontado'),
  ('Dados Cliente - Fase 2', '2.4.0', 'Op. Cr. Direito Creditório Descontado', 'Dados Cliente - Fase 2 - Op. Cr. Direito Creditório Descontado'),
  ('Dados Cliente - Fase 2', '2.0.1', 'Op. Créd. Adiantamento a Depositantes', 'Dados Cliente - Fase 2 - Op. Créd. Adiantamento a Depositantes'),
  ('Dados Cliente - Fase 2', '1.0.4', 'Op. Créd. Adiantamento a Depositantes', 'Dados Cliente - Fase 2 - Op. Créd. Adiantamento a Depositantes'),
  ('Dados Cliente - Fase 2', 'Não se Aplica', 'Op. Créd. Adiantamento a Depositantes', 'Dados Cliente - Fase 2 - Op. Créd. Adiantamento a Depositantes'),
  ('Dados Cliente - Fase 2', '2.1.0-rc.1', 'Op. Créd. Adiantamento a Depositantes', 'Dados Cliente - Fase 2 - Op. Créd. Adiantamento a Depositantes'),
  ('Dados Cliente - Fase 2', '2.1.0', 'Op. Créd. Adiantamento a Depositantes', 'Dados Cliente - Fase 2 - Op. Créd. Adiantamento a Depositantes'),
  ('Dados Cliente - Fase 2', '2.2.0', 'Op. Créd. Adiantamento a Depositantes', 'Dados Cliente - Fase 2 - Op. Créd. Adiantamento a Depositantes'),
  ('Dados Cliente - Fase 2', '2.3.0', 'Op. Créd. Adiantamento a Depositantes', 'Dados Cliente - Fase 2 - Op. Créd. Adiantamento a Depositantes'),
  ('Dados Cliente - Fase 2', '2.4.0', 'Op. Créd. Adiantamento a Depositantes', 'Dados Cliente - Fase 2 - Op. Créd. Adiantamento a Depositantes'),
  ('Dados Cliente - Fase 2', '2.5.0-beta.1', 'Op. Créd. Adiantamento a Depositantes', 'Dados Cliente - Fase 2 - Op. Créd. Adiantamento a Depositantes'),
  ('Dados Cliente - Fase 2', '2.5.0', 'Op. Créd. Adiantamento a Depositantes', 'Dados Cliente - Fase 2 - Op. Créd. Adiantamento a Depositantes'),
  ('Dados Cliente - Fase 2', '2.0.1', 'Op. Créd. Empréstimos', 'Dados Cliente - Fase 2 - Op. Créd. Empréstimos'),
  ('Dados Cliente - Fase 2', '1.0.4', 'Op. Créd. Empréstimos', 'Dados Cliente - Fase 2 - Op. Créd. Empréstimos'),
  ('Dados Cliente - Fase 2', 'Não se Aplica', 'Op. Créd. Empréstimos', 'Dados Cliente - Fase 2 - Op. Créd. Empréstimos'),
  ('Dados Cliente - Fase 2', '2.1.0-rc.1', 'Op. Créd. Empréstimos', 'Dados Cliente - Fase 2 - Op. Créd. Empréstimos'),
  ('Dados Cliente - Fase 2', '2.1.0', 'Op. Créd. Empréstimos', 'Dados Cliente - Fase 2 - Op. Créd. Empréstimos'),
  ('Dados Cliente - Fase 2', '2.2.0', 'Op. Créd. Empréstimos', 'Dados Cliente - Fase 2 - Op. Créd. Empréstimos'),
  ('Dados Cliente - Fase 2', '2.3.0', 'Op. Créd. Empréstimos', 'Dados Cliente - Fase 2 - Op. Créd. Empréstimos'),
  ('Dados Cliente - Fase 2', '2.4.0', 'Op. Créd. Empréstimos', 'Dados Cliente - Fase 2 - Op. Créd. Empréstimos'),
  ('Dados Cliente - Fase 2', '2.5.0', 'Op. Créd. Empréstimos', 'Dados Cliente - Fase 2 - Op. Créd. Empréstimos'),
  ('Dados Cliente - Fase 2', '2.6.0', 'Op. Créd. Empréstimos', 'Dados Cliente - Fase 2 - Op. Créd. Empréstimos'),
  ('Dados Cliente - Fase 2', '2.0.1', 'Op. Créd. Financiamentos', 'Dados Cliente - Fase 2 - Op. Créd. Financiamentos'),
  ('Dados Cliente - Fase 2', '1.0.4', 'Op. Créd. Financiamentos', 'Dados Cliente - Fase 2 - Op. Créd. Financiamentos'),
  ('Dados Cliente - Fase 2', 'Não se Aplica', 'Op. Créd. Financiamentos', 'Dados Cliente - Fase 2 - Op. Créd. Financiamentos'),
  ('Dados Cliente - Fase 2', '2.1.0', 'Op. Créd. Financiamentos', 'Dados Cliente - Fase 2 - Op. Créd. Financiamentos'),
  ('Dados Cliente - Fase 2', '2.1.0-rc.1', 'Op. Créd. Financiamentos', 'Dados Cliente - Fase 2 - Op. Créd. Financiamentos'),
  ('Dados Cliente - Fase 2', '2.2.0', 'Op. Créd. Financiamentos', 'Dados Cliente - Fase 2 - Op. Créd. Financiamentos'),
  ('Dados Cliente - Fase 2', '2.3.0', 'Op. Créd. Financiamentos', 'Dados Cliente - Fase 2 - Op. Créd. Financiamentos'),
  ('Dados Cliente - Fase 2', '2.4.0-beta.1', 'Op. Créd. Financiamentos', 'Dados Cliente - Fase 2 - Op. Créd. Financiamentos'),
  ('Dados Cliente - Fase 2', '2.4.0', 'Op. Créd. Financiamentos', 'Dados Cliente - Fase 2 - Op. Créd. Financiamentos'),
  ('Dados Cliente - Fase 2', '2.0.1', 'Resources', 'Dados Cliente - Fase 2 - Resources'),
  ('Dados Cliente - Fase 2', '1.0.2', 'Resources', 'Dados Cliente - Fase 2 - Resources'),
  ('Dados Cliente - Fase 2', 'Não se Aplica', 'Resources', 'Dados Cliente - Fase 2 - Resources'),
  ('Dados Cliente - Fase 2', '2.1.0', 'Resources', 'Dados Cliente - Fase 2 - Resources'),
  ('Dados Cliente - Fase 2', '3.0.0-beta.1', 'Resources', 'Dados Cliente - Fase 2 - Resources'),
  ('Dados Cliente - Fase 2', '2.1.0-rc1.0', 'Resources', 'Dados Cliente - Fase 2 - Resources'),
  ('Dados Cliente - Fase 2', '3.0.0-rc.1', 'Resources', 'Dados Cliente - Fase 2 - Resources'),
  ('Dados Cliente - Fase 2', '3.0.0-beta.2', 'Resources', 'Dados Cliente - Fase 2 - Resources'),
  ('Dados Cliente - Fase 2', '3.0.0', 'Resources', 'Dados Cliente - Fase 2 - Resources'),
  ('Dados Cliente - Fase 2', '3.1.0', 'Resources', 'Dados Cliente - Fase 2 - Resources'),
  ('Dados Cliente - Fase 4B', '1.0.0-rc1.0', 'Câmbio', 'Dados Cliente - Fase 4B - Câmbio'),
  ('Dados Cliente - Fase 4B', 'Não se Aplica', 'Câmbio', 'Dados Cliente - Fase 4B - Câmbio'),
  ('Dados Cliente - Fase 4B', '1.0.0-rc.2', 'Câmbio', 'Dados Cliente - Fase 4B - Câmbio'),
  ('Dados Cliente - Fase 4B', '1.0.0-rc.3', 'Câmbio', 'Dados Cliente - Fase 4B - Câmbio'),
  ('Dados Cliente - Fase 4B', '1.0.0-rc.4', 'Câmbio', 'Dados Cliente - Fase 4B - Câmbio'),
  ('Dados Cliente - Fase 4B', '1.0.0', 'Câmbio', 'Dados Cliente - Fase 4B - Câmbio'),
  ('Dados Cliente - Fase 4B', '1.1.0', 'Câmbio', 'Dados Cliente - Fase 4B - Câmbio'),
  ('Dados Cliente - Fase 4B - Investimento', '1.0.0-rc1.0', 'Fundos de Investimentos', 'Dados Cliente - Fase 4B - Investimento - Fundos de Investimentos'),
  ('Dados Cliente - Fase 4B - Investimento', 'Não se Aplica', 'Fundos de Investimentos', 'Dados Cliente - Fase 4B - Investimento - Fundos de Investimentos'),
  ('Dados Cliente - Fase 4B - Investimento', '1.0.2', 'Fundos de Investimentos', 'Dados Cliente - Fase 4B - Investimento - Fundos de Investimentos'),
  ('Dados Cliente - Fase 4B - Investimento', '1.0.0', 'Fundos de Investimentos', 'Dados Cliente - Fase 4B - Investimento - Fundos de Investimentos'),
  ('Dados Cliente - Fase 4B - Investimento', '1.1.0', 'Fundos de Investimentos', 'Dados Cliente - Fase 4B - Investimento - Fundos de Investimentos'),
  ('Dados Cliente - Fase 4B - Investimento', '1.0.0-rc1.0', 'Renda Fixa Bancária', 'Dados Cliente - Fase 4B - Investimento - Renda Fixa Bancária'),
  ('Dados Cliente - Fase 4B - Investimento', 'Não se Aplica', 'Renda Fixa Bancária', 'Dados Cliente - Fase 4B - Investimento - Renda Fixa Bancária'),
  ('Dados Cliente - Fase 4B - Investimento', '1.0.2', 'Renda Fixa Bancária', 'Dados Cliente - Fase 4B - Investimento - Renda Fixa Bancária'),
  ('Dados Cliente - Fase 4B - Investimento', '1.0.0', 'Renda Fixa Bancária', 'Dados Cliente - Fase 4B - Investimento - Renda Fixa Bancária'),
  ('Dados Cliente - Fase 4B - Investimento', '1.0.3', 'Renda Fixa Bancária', 'Dados Cliente - Fase 4B - Investimento - Renda Fixa Bancária'),
  ('Dados Cliente - Fase 4B - Investimento', '1.0.4', 'Renda Fixa Bancária', 'Dados Cliente - Fase 4B - Investimento - Renda Fixa Bancária'),
  ('Dados Cliente - Fase 4B - Investimento', '1.1.0', 'Renda Fixa Bancária', 'Dados Cliente - Fase 4B - Investimento - Renda Fixa Bancária'),
  ('Dados Cliente - Fase 4B - Investimento', '1.0.0-rc1.0', 'Renda Fixa Crédito', 'Dados Cliente - Fase 4B - Investimento - Renda Fixa Crédito'),
  ('Dados Cliente - Fase 4B - Investimento', 'Não se Aplica', 'Renda Fixa Crédito', 'Dados Cliente - Fase 4B - Investimento - Renda Fixa Crédito'),
  ('Dados Cliente - Fase 4B - Investimento', '1.0.0', 'Renda Fixa Crédito', 'Dados Cliente - Fase 4B - Investimento - Renda Fixa Crédito'),
  ('Dados Cliente - Fase 4B - Investimento', '1.0.1', 'Renda Fixa Crédito', 'Dados Cliente - Fase 4B - Investimento - Renda Fixa Crédito'),
  ('Dados Cliente - Fase 4B - Investimento', '1.0.2', 'Renda Fixa Crédito', 'Dados Cliente - Fase 4B - Investimento - Renda Fixa Crédito'),
  ('Dados Cliente - Fase 4B - Investimento', '1.0.3', 'Renda Fixa Crédito', 'Dados Cliente - Fase 4B - Investimento - Renda Fixa Crédito'),
  ('Dados Cliente - Fase 4B - Investimento', '1.1.0', 'Renda Fixa Crédito', 'Dados Cliente - Fase 4B - Investimento - Renda Fixa Crédito'),
  ('Dados Cliente - Fase 4B - Investimento', '1.0.0-rc1.0', 'Renda Variável', 'Dados Cliente - Fase 4B - Investimento - Renda Variável'),
  ('Dados Cliente - Fase 4B - Investimento', 'Não se Aplica', 'Renda Variável', 'Dados Cliente - Fase 4B - Investimento - Renda Variável'),
  ('Dados Cliente - Fase 4B - Investimento', '1.0.2', 'Renda Variável', 'Dados Cliente - Fase 4B - Investimento - Renda Variável'),
  ('Dados Cliente - Fase 4B - Investimento', '1.0.0', 'Renda Variável', 'Dados Cliente - Fase 4B - Investimento - Renda Variável'),
  ('Dados Cliente - Fase 4B - Investimento', '1.1.0', 'Renda Variável', 'Dados Cliente - Fase 4B - Investimento - Renda Variável'),
  ('Dados Cliente - Fase 4B - Investimento', '1.2.0', 'Renda Variável', 'Dados Cliente - Fase 4B - Investimento - Renda Variável'),
  ('Dados Cliente - Fase 4B - Investimento', '1.2.1', 'Renda Variável', 'Dados Cliente - Fase 4B - Investimento - Renda Variável'),
  ('Dados Cliente - Fase 4B - Investimento', '1.3.0', 'Renda Variável', 'Dados Cliente - Fase 4B - Investimento - Renda Variável'),
  ('Dados Cliente - Fase 4B - Investimento', '1.0.0-rc1.0', 'Títulos Tesouro Direto', 'Dados Cliente - Fase 4B - Investimento - Títulos Tesouro Direto'),
  ('Dados Cliente - Fase 4B - Investimento', 'Não se Aplica', 'Títulos Tesouro Direto', 'Dados Cliente - Fase 4B - Investimento - Títulos Tesouro Direto'),
  ('Dados Cliente - Fase 4B - Investimento', '1.0.1', 'Títulos Tesouro Direto', 'Dados Cliente - Fase 4B - Investimento - Títulos Tesouro Direto'),
  ('Dados Cliente - Fase 4B - Investimento', '1.0.0', 'Títulos Tesouro Direto', 'Dados Cliente - Fase 4B - Investimento - Títulos Tesouro Direto'),
  ('Dados Cliente - Fase 4B - Investimento', '1.0.2', 'Títulos Tesouro Direto', 'Dados Cliente - Fase 4B - Investimento - Títulos Tesouro Direto'),
  ('Dados Cliente - Fase 4B - Investimento', '1.1.0', 'Títulos Tesouro Direto', 'Dados Cliente - Fase 4B - Investimento - Títulos Tesouro Direto'),
  ('Métricas', 'Não se Aplica', 'Admin', 'Métricas - Admin'),
  ('Métricas', '2.0.0-beta.1', 'Admin', 'Métricas - Admin'),
  ('Métricas', '2.0.0', 'Admin', 'Métricas - Admin'),
  ('Métricas', '1.0.2', 'Admin', 'Métricas - Admin'),
  ('Métricas', '2.0.1', 'Admin', 'Métricas - Admin'),
  ('Métricas', 'Não se Aplica', 'Comum', 'Métricas - Comum'),
  ('Métricas', '2.0.1', 'Comum', 'Métricas - Comum'),
  ('Métricas', '2.0.0-beta.1', 'Comum', 'Métricas - Comum'),
  ('Métricas', '2.0.0-beta.2', 'Comum', 'Métricas - Comum'),
  ('Métricas', '1.0.2', 'Comum', 'Métricas - Comum'),
  ('Não se Aplica', 'Não se Aplica', 'Não se Aplica', 'Não se Aplica - Não se Aplica, Não se Aplica'),
  ('Portabilidade de Crédito', '1.0.0-beta.1', 'Não se Aplica', 'Portabilidade de Crédito - Não se Aplica'),
  ('Portabilidade de Crédito', 'Não se Aplica', 'Não se Aplica', 'Portabilidade de Crédito - Não se Aplica, Não se Aplica'),
  ('Portabilidade de Crédito', '1.0.0-beta.2', 'Não se Aplica', 'Portabilidade de Crédito - Não se Aplica'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '1.2.0', 'Agendamento', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '1.2.0', 'Agendamento single', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento single'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '1.2.0', 'Imediato', 'Serviços - Fase 3 - Iniciação de Pagamentos - Imediato'),
  ('Serviços - Fase 3', '1.2.0', 'Iniciação de Pagamentos', 'Serviços - Fase 3 - Iniciação de Pagamentos'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '2.0.0', 'Agendamento', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '2.0.0', 'Agendamento single', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento single'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '2.0.0', 'Imediato', 'Serviços - Fase 3 - Iniciação de Pagamentos - Imediato'),
  ('Serviços - Fase 3', '2.0.0', 'Iniciação de Pagamentos', 'Serviços - Fase 3 - Iniciação de Pagamentos'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', 'Não se Aplica', 'Agendamento', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento, Não se Aplica'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', 'Não se Aplica', 'Agendamento single', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento single, Não se Aplica'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', 'Não se Aplica', 'Imediato', 'Serviços - Fase 3 - Iniciação de Pagamentos - Imediato, Não se Aplica'),
  ('Serviços - Fase 3', 'Não se Aplica', 'Iniciação de Pagamentos', 'Serviços - Fase 3 - Iniciação de Pagamentos, Não se Aplica'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '3.0.0', 'Agendamento', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '3.0.0', 'Agendamento single', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento single'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '3.0.0', 'Imediato', 'Serviços - Fase 3 - Iniciação de Pagamentos - Imediato'),
  ('Serviços - Fase 3', '3.0.0', 'Iniciação de Pagamentos', 'Serviços - Fase 3 - Iniciação de Pagamentos'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '4.0.0-beta.2', 'Agendamento', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '4.0.0-beta.2', 'Agendamento single', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento single'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '4.0.0-beta.2', 'Imediato', 'Serviços - Fase 3 - Iniciação de Pagamentos - Imediato'),
  ('Serviços - Fase 3', '4.0.0-beta.2', 'Iniciação de Pagamentos', 'Serviços - Fase 3 - Iniciação de Pagamentos'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '3.0.0-beta1.0', 'Agendamento', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '3.0.0-beta1.0', 'Agendamento single', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento single'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '3.0.0-beta1.0', 'Imediato', 'Serviços - Fase 3 - Iniciação de Pagamentos - Imediato'),
  ('Serviços - Fase 3', '3.0.0-beta1.0', 'Iniciação de Pagamentos', 'Serviços - Fase 3 - Iniciação de Pagamentos'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '4.0.0-beta.3', 'Agendamento', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '4.0.0-beta.3', 'Agendamento single', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento single'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '4.0.0-beta.3', 'Imediato', 'Serviços - Fase 3 - Iniciação de Pagamentos - Imediato'),
  ('Serviços - Fase 3', '4.0.0-beta.3', 'Iniciação de Pagamentos', 'Serviços - Fase 3 - Iniciação de Pagamentos'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '4.0.0-rc.1', 'Agendamento', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '4.0.0-rc.1', 'Agendamento single', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento single'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '4.0.0-rc.1', 'Imediato', 'Serviços - Fase 3 - Iniciação de Pagamentos - Imediato'),
  ('Serviços - Fase 3', '4.0.0-rc.1', 'Iniciação de Pagamentos', 'Serviços - Fase 3 - Iniciação de Pagamentos'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '4.0.0-beta.1', 'Agendamento', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '4.0.0-beta.1', 'Agendamento single', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento single'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '4.0.0-beta.1', 'Imediato', 'Serviços - Fase 3 - Iniciação de Pagamentos - Imediato'),
  ('Serviços - Fase 3', '4.0.0-beta.1', 'Iniciação de Pagamentos', 'Serviços - Fase 3 - Iniciação de Pagamentos'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '4.0.0-beta.4', 'Agendamento', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '4.0.0-beta.4', 'Agendamento single', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento single'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '4.0.0-beta.4', 'Imediato', 'Serviços - Fase 3 - Iniciação de Pagamentos - Imediato'),
  ('Serviços - Fase 3', '4.0.0-beta.4', 'Iniciação de Pagamentos', 'Serviços - Fase 3 - Iniciação de Pagamentos'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '4.0.0', 'Agendamento', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '4.0.0', 'Agendamento single', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento single'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '4.0.0', 'Imediato', 'Serviços - Fase 3 - Iniciação de Pagamentos - Imediato'),
  ('Serviços - Fase 3', '4.0.0', 'Iniciação de Pagamentos', 'Serviços - Fase 3 - Iniciação de Pagamentos'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '4.0.1', 'Agendamento', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '4.0.1', 'Agendamento single', 'Serviços - Fase 3 - Iniciação de Pagamentos - Agendamento single'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos', '4.0.1', 'Imediato', 'Serviços - Fase 3 - Iniciação de Pagamentos - Imediato'),
  ('Serviços - Fase 3', '4.0.1', 'Iniciação de Pagamentos', 'Serviços - Fase 3 - Iniciação de Pagamentos'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Pix Automático', 'Geração do recurringPaymentId'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Pix Automático', 'Pagamentos Realizados com Sucesso'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Pix Automático', 'Pagamentos com Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Pix Automático', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos - Pix Automático, Não se Aplica'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Pix Automático', 'Solicitação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Pix Automático', 'Criação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Pix Automático', 'Geração do recurringConsentId (Não clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Pix Automático', 'Criação de Consentimentos Solicitados Desconsiderando Não Client'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Pix Automático', 'Geração do recurringConsentId (Clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Pix Automático', 'Início da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Pix Automático', 'Conclusão da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Pix Automático', 'Autorização do Cliente'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Pix Automático', 'Redirecionamento para ITP'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Pix Automático', 'Emissão do Authorisation Code'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Pix Automático', 'Geração do Access Token'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Pix Automático', 'Pagamentos Recebidos - Todas as chamadas do post/pix'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Sweeping', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos - Sweeping, Não se Aplica'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Sweeping', 'Solicitação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Sweeping', 'Criação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Sweeping', 'Geração do recurringConsentId (Não clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Sweeping', 'Criação de Consentimentos Solicitados Desconsiderando Não Client'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Sweeping', 'Geração do recurringConsentId (Clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Sweeping', 'Início da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Sweeping', 'Conclusão da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Sweeping', 'Autorização do Cliente'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Sweeping', 'Redirecionamento para ITP'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Sweeping', 'Emissão do Authorisation Code'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Sweeping', 'Geração do Access Token'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Sweeping', 'Pagamentos Recebidos - Todas as chamadas do post/pix'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Sweeping', 'Geração do recurringPaymentId'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Sweeping', 'Pagamentos Realizados com Sucesso'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'Sweeping', 'Pagamentos com Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', 'Não se Aplica', 'VRP', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos - VRP, Não se Aplica'),
  ('Serviços - Fase 3', '1.0.0', 'Iniciação de Pagamentos Automáticos', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Pix Automático', 'Geração do recurringPaymentId'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Pix Automático', 'Pagamentos Realizados com Sucesso'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Pix Automático', 'Pagamentos com Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Pix Automático', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos - Pix Automático'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Pix Automático', 'Solicitação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Pix Automático', 'Criação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Pix Automático', 'Geração do recurringConsentId (Não clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Pix Automático', 'Criação de Consentimentos Solicitados Desconsiderando Não Client'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Pix Automático', 'Geração do recurringConsentId (Clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Pix Automático', 'Início da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Pix Automático', 'Conclusão da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Pix Automático', 'Autorização do Cliente'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Pix Automático', 'Redirecionamento para ITP'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Pix Automático', 'Emissão do Authorisation Code'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Pix Automático', 'Geração do Access Token'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Pix Automático', 'Pagamentos Recebidos - Todas as chamadas do post/pix'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Sweeping', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos - Sweeping'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Sweeping', 'Solicitação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Sweeping', 'Criação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Sweeping', 'Geração do recurringConsentId (Não clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Sweeping', 'Criação de Consentimentos Solicitados Desconsiderando Não Client'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Sweeping', 'Geração do recurringConsentId (Clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Sweeping', 'Início da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Sweeping', 'Conclusão da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Sweeping', 'Autorização do Cliente'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Sweeping', 'Redirecionamento para ITP'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Sweeping', 'Emissão do Authorisation Code'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Sweeping', 'Geração do Access Token'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Sweeping', 'Pagamentos Recebidos - Todas as chamadas do post/pix'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Sweeping', 'Geração do recurringPaymentId'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Sweeping', 'Pagamentos Realizados com Sucesso'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'Sweeping', 'Pagamentos com Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '1.0.0', 'VRP', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos - VRP'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Pix Automático', 'Geração do recurringPaymentId'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Pix Automático', 'Pagamentos Realizados com Sucesso'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Pix Automático', 'Pagamentos com Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Pix Automático', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos - Pix Automático'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Pix Automático', 'Solicitação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Pix Automático', 'Criação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Pix Automático', 'Geração do recurringConsentId (Não clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Pix Automático', 'Criação de Consentimentos Solicitados Desconsiderando Não Client'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Pix Automático', 'Geração do recurringConsentId (Clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Pix Automático', 'Início da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Pix Automático', 'Conclusão da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Pix Automático', 'Autorização do Cliente'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Pix Automático', 'Redirecionamento para ITP'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Pix Automático', 'Emissão do Authorisation Code'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Pix Automático', 'Geração do Access Token'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Pix Automático', 'Pagamentos Recebidos - Todas as chamadas do post/pix'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Sweeping', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos - Sweeping'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Sweeping', 'Solicitação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Sweeping', 'Criação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Sweeping', 'Geração do recurringConsentId (Não clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Sweeping', 'Criação de Consentimentos Solicitados Desconsiderando Não Client'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Sweeping', 'Geração do recurringConsentId (Clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Sweeping', 'Início da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Sweeping', 'Conclusão da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Sweeping', 'Autorização do Cliente'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Sweeping', 'Redirecionamento para ITP'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Sweeping', 'Emissão do Authorisation Code'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Sweeping', 'Geração do Access Token'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Sweeping', 'Pagamentos Recebidos - Todas as chamadas do post/pix'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Sweeping', 'Geração do recurringPaymentId'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Sweeping', 'Pagamentos Realizados com Sucesso'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'Sweeping', 'Pagamentos com Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.0.0', 'VRP', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos - VRP'),
  ('Serviços - Fase 3', '2.0.0', 'Iniciação de Pagamentos Automáticos', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Pix Automático', 'Geração do recurringPaymentId'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Pix Automático', 'Pagamentos Realizados com Sucesso'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Pix Automático', 'Pagamentos com Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Pix Automático', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos - Pix Automático'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Pix Automático', 'Solicitação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Pix Automático', 'Criação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Pix Automático', 'Geração do recurringConsentId (Não clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Pix Automático', 'Criação de Consentimentos Solicitados Desconsiderando Não Client'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Pix Automático', 'Geração do recurringConsentId (Clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Pix Automático', 'Início da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Pix Automático', 'Conclusão da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Pix Automático', 'Autorização do Cliente'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Pix Automático', 'Redirecionamento para ITP'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Pix Automático', 'Emissão do Authorisation Code'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Pix Automático', 'Geração do Access Token'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Pix Automático', 'Pagamentos Recebidos - Todas as chamadas do post/pix'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Sweeping', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos - Sweeping'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Sweeping', 'Solicitação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Sweeping', 'Criação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Sweeping', 'Geração do recurringConsentId (Não clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Sweeping', 'Criação de Consentimentos Solicitados Desconsiderando Não Client'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Sweeping', 'Geração do recurringConsentId (Clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Sweeping', 'Início da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Sweeping', 'Conclusão da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Sweeping', 'Autorização do Cliente'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Sweeping', 'Redirecionamento para ITP'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Sweeping', 'Emissão do Authorisation Code'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Sweeping', 'Geração do Access Token'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Sweeping', 'Pagamentos Recebidos - Todas as chamadas do post/pix'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Sweeping', 'Geração do recurringPaymentId'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Sweeping', 'Pagamentos Realizados com Sucesso'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'Sweeping', 'Pagamentos com Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.1.0', 'VRP', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos - VRP'),
  ('Serviços - Fase 3', '2.1.0', 'Iniciação de Pagamentos Automáticos', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Pix Automático', 'Geração do recurringPaymentId'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Pix Automático', 'Pagamentos Realizados com Sucesso'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Pix Automático', 'Pagamentos com Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Pix Automático', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos - Pix Automático'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Pix Automático', 'Solicitação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Pix Automático', 'Criação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Pix Automático', 'Geração do recurringConsentId (Não clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Pix Automático', 'Criação de Consentimentos Solicitados Desconsiderando Não Client'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Pix Automático', 'Geração do recurringConsentId (Clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Pix Automático', 'Início da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Pix Automático', 'Conclusão da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Pix Automático', 'Autorização do Cliente'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Pix Automático', 'Redirecionamento para ITP'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Pix Automático', 'Emissão do Authorisation Code'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Pix Automático', 'Geração do Access Token'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Pix Automático', 'Pagamentos Recebidos - Todas as chamadas do post/pix'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Sweeping', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos - Sweeping'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Sweeping', 'Solicitação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Sweeping', 'Criação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Sweeping', 'Geração do recurringConsentId (Não clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Sweeping', 'Criação de Consentimentos Solicitados Desconsiderando Não Client'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Sweeping', 'Geração do recurringConsentId (Clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Sweeping', 'Início da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Sweeping', 'Conclusão da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Sweeping', 'Autorização do Cliente'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Sweeping', 'Redirecionamento para ITP'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Sweeping', 'Emissão do Authorisation Code'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Sweeping', 'Geração do Access Token'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Sweeping', 'Pagamentos Recebidos - Todas as chamadas do post/pix'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Sweeping', 'Geração do recurringPaymentId'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Sweeping', 'Pagamentos Realizados com Sucesso'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'Sweeping', 'Pagamentos com Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.1', 'VRP', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos - VRP'),
  ('Serviços - Fase 3', '2.2.0-rc.1', 'Iniciação de Pagamentos Automáticos', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Pix Automático', 'Geração do recurringPaymentId'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Pix Automático', 'Pagamentos Realizados com Sucesso'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Pix Automático', 'Pagamentos com Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Pix Automático', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos - Pix Automático'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Pix Automático', 'Solicitação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Pix Automático', 'Criação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Pix Automático', 'Geração do recurringConsentId (Não clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Pix Automático', 'Criação de Consentimentos Solicitados Desconsiderando Não Client'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Pix Automático', 'Geração do recurringConsentId (Clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Pix Automático', 'Início da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Pix Automático', 'Conclusão da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Pix Automático', 'Autorização do Cliente'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Pix Automático', 'Redirecionamento para ITP'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Pix Automático', 'Emissão do Authorisation Code'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Pix Automático', 'Geração do Access Token'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Pix Automático', 'Pagamentos Recebidos - Todas as chamadas do post/pix'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Sweeping', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos - Sweeping'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Sweeping', 'Solicitação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Sweeping', 'Criação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Sweeping', 'Geração do recurringConsentId (Não clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Sweeping', 'Criação de Consentimentos Solicitados Desconsiderando Não Client'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Sweeping', 'Geração do recurringConsentId (Clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Sweeping', 'Início da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Sweeping', 'Conclusão da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Sweeping', 'Autorização do Cliente'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Sweeping', 'Redirecionamento para ITP'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Sweeping', 'Emissão do Authorisation Code'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Sweeping', 'Geração do Access Token'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Sweeping', 'Pagamentos Recebidos - Todas as chamadas do post/pix'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Sweeping', 'Geração do recurringPaymentId'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Sweeping', 'Pagamentos Realizados com Sucesso'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'Sweeping', 'Pagamentos com Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0-rc.2', 'VRP', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos - VRP'),
  ('Serviços - Fase 3', '2.2.0-rc.2', 'Iniciação de Pagamentos Automáticos', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Pix Automático', 'Geração do recurringPaymentId'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Pix Automático', 'Pagamentos Realizados com Sucesso'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Pix Automático', 'Pagamentos com Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Pix Automático', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos - Pix Automático'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Pix Automático', 'Solicitação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Pix Automático', 'Criação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Pix Automático', 'Geração do recurringConsentId (Não clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Pix Automático', 'Criação de Consentimentos Solicitados Desconsiderando Não Client'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Pix Automático', 'Geração do recurringConsentId (Clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Pix Automático', 'Início da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Pix Automático', 'Conclusão da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Pix Automático', 'Autorização do Cliente'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Pix Automático', 'Redirecionamento para ITP'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Pix Automático', 'Emissão do Authorisation Code'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Pix Automático', 'Geração do Access Token'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Pix Automático', 'Pagamentos Recebidos - Todas as chamadas do post/pix'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Sweeping', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos - Sweeping'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Sweeping', 'Solicitação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Sweeping', 'Criação do Consentimento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Sweeping', 'Geração do recurringConsentId (Não clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Sweeping', 'Criação de Consentimentos Solicitados Desconsiderando Não Client'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Sweeping', 'Geração do recurringConsentId (Clientes)'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Sweeping', 'Início da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Sweeping', 'Conclusão da Autenticação'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Sweeping', 'Autorização do Cliente'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Sweeping', 'Redirecionamento para ITP'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Sweeping', 'Emissão do Authorisation Code'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Sweeping', 'Geração do Access Token'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Sweeping', 'Pagamentos Recebidos - Todas as chamadas do post/pix'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Sweeping', 'Geração do recurringPaymentId'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Sweeping', 'Pagamentos Realizados com Sucesso'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'Sweeping', 'Pagamentos com Agendamento'),
  ('Serviços - Fase 3 - Iniciação de Pagamentos Automáticos', '2.2.0', 'VRP', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos - VRP'),
  ('Serviços - Fase 3', '2.2.0', 'Iniciação de Pagamentos Automáticos', 'Serviços - Fase 3 - Iniciação de Pagamentos Automáticos'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.2.0', 'Jornada sem Redirecionamento', 'Associação de credencial FIDO2 ao vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.2.0', 'Jornada sem Redirecionamento', 'Autorização de um consentimento de pagamento de JSR'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.2.0', 'Jornada sem Redirecionamento', 'Consulta de vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.2.0', 'Jornada sem Redirecionamento', 'Criação de vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.2.0', 'Jornada sem Redirecionamento', 'Envio de sinais de risco para inici. do vínculo de disposítivo'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.2.0', 'Jornada sem Redirecionamento', 'Indisponibilidade'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.2.0', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para a criação de cred. FIDO02'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.2.0', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para autenticação FIDO2'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.2.0', 'Jornada sem Redirecionamento', 'Outros'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.2.0', 'Jornada sem Redirecionamento', 'Revogação ou rejeição do vínculo de conta'),
  ('Serviços - Fase 3', '1.2.0', 'Pagamentos sem Redirecionamento', 'Serviços - Fase 3 - Pagamentos sem Redirecionamento'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.1.0', 'Jornada sem Redirecionamento', 'Associação de credencial FIDO2 ao vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.1.0', 'Jornada sem Redirecionamento', 'Autorização de um consentimento de pagamento de JSR'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.1.0', 'Jornada sem Redirecionamento', 'Consulta de vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.1.0', 'Jornada sem Redirecionamento', 'Criação de vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.1.0', 'Jornada sem Redirecionamento', 'Envio de sinais de risco para inici. do vínculo de disposítivo'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.1.0', 'Jornada sem Redirecionamento', 'Indisponibilidade'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.1.0', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para a criação de cred. FIDO02'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.1.0', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para autenticação FIDO2'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.1.0', 'Jornada sem Redirecionamento', 'Outros'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.1.0', 'Jornada sem Redirecionamento', 'Revogação ou rejeição do vínculo de conta'),
  ('Serviços - Fase 3', '1.1.0', 'Pagamentos sem Redirecionamento', 'Serviços - Fase 3 - Pagamentos sem Redirecionamento'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', 'Não se Aplica', 'Jornada sem Redirecionamento', 'Associação de credencial FIDO2 ao vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', 'Não se Aplica', 'Jornada sem Redirecionamento', 'Autorização de um consentimento de pagamento de JSR'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', 'Não se Aplica', 'Jornada sem Redirecionamento', 'Consulta de vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', 'Não se Aplica', 'Jornada sem Redirecionamento', 'Criação de vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', 'Não se Aplica', 'Jornada sem Redirecionamento', 'Envio de sinais de risco para inici. do vínculo de disposítivo'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', 'Não se Aplica', 'Jornada sem Redirecionamento', 'Indisponibilidade'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', 'Não se Aplica', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para a criação de cred. FIDO02'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', 'Não se Aplica', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para autenticação FIDO2'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', 'Não se Aplica', 'Jornada sem Redirecionamento', 'Outros'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', 'Não se Aplica', 'Jornada sem Redirecionamento', 'Revogação ou rejeição do vínculo de conta'),
  ('Serviços - Fase 3', 'Não se Aplica', 'Pagamentos sem Redirecionamento', 'Serviços - Fase 3 - Pagamentos sem Redirecionamento'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.3.1', 'Jornada sem Redirecionamento', 'Associação de credencial FIDO2 ao vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.3.1', 'Jornada sem Redirecionamento', 'Autorização de um consentimento de pagamento de JSR'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.3.1', 'Jornada sem Redirecionamento', 'Consulta de vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.3.1', 'Jornada sem Redirecionamento', 'Criação de vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.3.1', 'Jornada sem Redirecionamento', 'Envio de sinais de risco para inici. do vínculo de disposítivo'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.3.1', 'Jornada sem Redirecionamento', 'Indisponibilidade'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.3.1', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para a criação de cred. FIDO02'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.3.1', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para autenticação FIDO2'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.3.1', 'Jornada sem Redirecionamento', 'Outros'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '1.3.1', 'Jornada sem Redirecionamento', 'Revogação ou rejeição do vínculo de conta'),
  ('Serviços - Fase 3', '1.3.1', 'Pagamentos sem Redirecionamento', 'Serviços - Fase 3 - Pagamentos sem Redirecionamento'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.0.0-beta.1', 'Jornada sem Redirecionamento', 'Associação de credencial FIDO2 ao vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.0.0-beta.1', 'Jornada sem Redirecionamento', 'Autorização de um consentimento de pagamento de JSR'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.0.0-beta.1', 'Jornada sem Redirecionamento', 'Consulta de vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.0.0-beta.1', 'Jornada sem Redirecionamento', 'Criação de vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.0.0-beta.1', 'Jornada sem Redirecionamento', 'Envio de sinais de risco para inici. do vínculo de disposítivo'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.0.0-beta.1', 'Jornada sem Redirecionamento', 'Indisponibilidade'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.0.0-beta.1', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para a criação de cred. FIDO02'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.0.0-beta.1', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para autenticação FIDO2'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.0.0-beta.1', 'Jornada sem Redirecionamento', 'Outros'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.0.0-beta.1', 'Jornada sem Redirecionamento', 'Revogação ou rejeição do vínculo de conta'),
  ('Serviços - Fase 3', '2.0.0-beta.1', 'Pagamentos sem Redirecionamento', 'Serviços - Fase 3 - Pagamentos sem Redirecionamento'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.0.0', 'Jornada sem Redirecionamento', 'Associação de credencial FIDO2 ao vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.0.0', 'Jornada sem Redirecionamento', 'Autorização de um consentimento de pagamento de JSR'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.0.0', 'Jornada sem Redirecionamento', 'Consulta de vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.0.0', 'Jornada sem Redirecionamento', 'Criação de vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.0.0', 'Jornada sem Redirecionamento', 'Envio de sinais de risco para inici. do vínculo de disposítivo'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.0.0', 'Jornada sem Redirecionamento', 'Indisponibilidade'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.0.0', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para a criação de cred. FIDO02'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.0.0', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para autenticação FIDO2'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.0.0', 'Jornada sem Redirecionamento', 'Outros'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.0.0', 'Jornada sem Redirecionamento', 'Revogação ou rejeição do vínculo de conta'),
  ('Serviços - Fase 3', '2.0.0', 'Pagamentos sem Redirecionamento', 'Serviços - Fase 3 - Pagamentos sem Redirecionamento'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.1.0', 'Jornada sem Redirecionamento', 'Associação de credencial FIDO2 ao vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.1.0', 'Jornada sem Redirecionamento', 'Autorização de um consentimento de pagamento de JSR'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.1.0', 'Jornada sem Redirecionamento', 'Consulta de vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.1.0', 'Jornada sem Redirecionamento', 'Criação de vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.1.0', 'Jornada sem Redirecionamento', 'Envio de sinais de risco para inici. do vínculo de disposítivo'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.1.0', 'Jornada sem Redirecionamento', 'Indisponibilidade'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.1.0', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para a criação de cred. FIDO02'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.1.0', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para autenticação FIDO2'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.1.0', 'Jornada sem Redirecionamento', 'Outros'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.1.0', 'Jornada sem Redirecionamento', 'Revogação ou rejeição do vínculo de conta'),
  ('Serviços - Fase 3', '2.1.0', 'Pagamentos sem Redirecionamento', 'Serviços - Fase 3 - Pagamentos sem Redirecionamento'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.2.0-rc.1', 'Jornada sem Redirecionamento', 'Associação de credencial FIDO2 ao vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.2.0-rc.1', 'Jornada sem Redirecionamento', 'Autorização de um consentimento de pagamento de JSR'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.2.0-rc.1', 'Jornada sem Redirecionamento', 'Consulta de vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.2.0-rc.1', 'Jornada sem Redirecionamento', 'Criação de vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.2.0-rc.1', 'Jornada sem Redirecionamento', 'Envio de sinais de risco para inici. do vínculo de disposítivo'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.2.0-rc.1', 'Jornada sem Redirecionamento', 'Indisponibilidade'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.2.0-rc.1', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para a criação de cred. FIDO02'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.2.0-rc.1', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para autenticação FIDO2'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.2.0-rc.1', 'Jornada sem Redirecionamento', 'Outros'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.2.0-rc.1', 'Jornada sem Redirecionamento', 'Revogação ou rejeição do vínculo de conta'),
  ('Serviços - Fase 3', '2.2.0-rc.1', 'Pagamentos sem Redirecionamento', 'Serviços - Fase 3 - Pagamentos sem Redirecionamento'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.2.0', 'Jornada sem Redirecionamento', 'Associação de credencial FIDO2 ao vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.2.0', 'Jornada sem Redirecionamento', 'Autorização de um consentimento de pagamento de JSR'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.2.0', 'Jornada sem Redirecionamento', 'Consulta de vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.2.0', 'Jornada sem Redirecionamento', 'Criação de vínculo de conta'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.2.0', 'Jornada sem Redirecionamento', 'Envio de sinais de risco para inici. do vínculo de disposítivo'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.2.0', 'Jornada sem Redirecionamento', 'Indisponibilidade'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.2.0', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para a criação de cred. FIDO02'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.2.0', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para autenticação FIDO2'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.2.0', 'Jornada sem Redirecionamento', 'Outros'),
  ('Serviços - Fase 3 - Pagamentos sem Redirecionamento', '2.2.0', 'Jornada sem Redirecionamento', 'Revogação ou rejeição do vínculo de conta'),
  ('Serviços - Fase 3', '2.2.0', 'Pagamentos sem Redirecionamento', 'Serviços - Fase 3 - Pagamentos sem Redirecionamento'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', 'Não se Aplica', 'Jornada sem Redirecionamento', 'Associação de credencial FIDO2 ao vínculo de conta'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', 'Não se Aplica', 'Jornada sem Redirecionamento', 'Autorização de um consentimento de pagamento de JSR'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', 'Não se Aplica', 'Jornada sem Redirecionamento', 'Consulta de vínculo de conta'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', 'Não se Aplica', 'Jornada sem Redirecionamento', 'Criação de vínculo de conta'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', 'Não se Aplica', 'Jornada sem Redirecionamento', 'Envio de sinais de risco para inici. do vínculo de disposítivo'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', 'Não se Aplica', 'Jornada sem Redirecionamento', 'Indisponibilidade'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', 'Não se Aplica', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para a criação de cred. FIDO02'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', 'Não se Aplica', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para autenticação FIDO2'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', 'Não se Aplica', 'Jornada sem Redirecionamento', 'Outros'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', 'Não se Aplica', 'Jornada sem Redirecionamento', 'Revogação ou rejeição do vínculo de conta'),
  ('Serviços - Fase 3', 'Não se Aplica', 'Vínculo de Dispositivo', 'Serviços - Fase 3 - Vínculo de Dispositivo'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '1.0.0', 'Jornada sem Redirecionamento', 'Associação de credencial FIDO2 ao vínculo de conta'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '1.0.0', 'Jornada sem Redirecionamento', 'Autorização de um consentimento de pagamento de JSR'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '1.0.0', 'Jornada sem Redirecionamento', 'Consulta de vínculo de conta'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '1.0.0', 'Jornada sem Redirecionamento', 'Criação de vínculo de conta'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '1.0.0', 'Jornada sem Redirecionamento', 'Envio de sinais de risco para inici. do vínculo de disposítivo'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '1.0.0', 'Jornada sem Redirecionamento', 'Indisponibilidade'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '1.0.0', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para a criação de cred. FIDO02'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '1.0.0', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para autenticação FIDO2'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '1.0.0', 'Jornada sem Redirecionamento', 'Outros'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '1.0.0', 'Jornada sem Redirecionamento', 'Revogação ou rejeição do vínculo de conta'),
  ('Serviços - Fase 3', '1.0.0', 'Vínculo de Dispositivo', 'Serviços - Fase 3 - Vínculo de Dispositivo'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '1.3.1', 'Jornada sem Redirecionamento', 'Associação de credencial FIDO2 ao vínculo de conta'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '1.3.1', 'Jornada sem Redirecionamento', 'Autorização de um consentimento de pagamento de JSR'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '1.3.1', 'Jornada sem Redirecionamento', 'Consulta de vínculo de conta'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '1.3.1', 'Jornada sem Redirecionamento', 'Criação de vínculo de conta'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '1.3.1', 'Jornada sem Redirecionamento', 'Envio de sinais de risco para inici. do vínculo de disposítivo'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '1.3.1', 'Jornada sem Redirecionamento', 'Indisponibilidade'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '1.3.1', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para a criação de cred. FIDO02'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '1.3.1', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para autenticação FIDO2'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '1.3.1', 'Jornada sem Redirecionamento', 'Outros'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '1.3.1', 'Jornada sem Redirecionamento', 'Revogação ou rejeição do vínculo de conta'),
  ('Serviços - Fase 3', '1.3.1', 'Vínculo de Dispositivo', 'Serviços - Fase 3 - Vínculo de Dispositivo'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.0.0', 'Jornada sem Redirecionamento', 'Associação de credencial FIDO2 ao vínculo de conta'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.0.0', 'Jornada sem Redirecionamento', 'Autorização de um consentimento de pagamento de JSR'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.0.0', 'Jornada sem Redirecionamento', 'Consulta de vínculo de conta'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.0.0', 'Jornada sem Redirecionamento', 'Criação de vínculo de conta'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.0.0', 'Jornada sem Redirecionamento', 'Envio de sinais de risco para inici. do vínculo de disposítivo'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.0.0', 'Jornada sem Redirecionamento', 'Indisponibilidade'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.0.0', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para a criação de cred. FIDO02'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.0.0', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para autenticação FIDO2'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.0.0', 'Jornada sem Redirecionamento', 'Outros'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.0.0', 'Jornada sem Redirecionamento', 'Revogação ou rejeição do vínculo de conta'),
  ('Serviços - Fase 3', '2.0.0', 'Vínculo de Dispositivo', 'Serviços - Fase 3 - Vínculo de Dispositivo'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.1.0', 'Jornada sem Redirecionamento', 'Associação de credencial FIDO2 ao vínculo de conta'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.1.0', 'Jornada sem Redirecionamento', 'Autorização de um consentimento de pagamento de JSR'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.1.0', 'Jornada sem Redirecionamento', 'Consulta de vínculo de conta'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.1.0', 'Jornada sem Redirecionamento', 'Criação de vínculo de conta'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.1.0', 'Jornada sem Redirecionamento', 'Envio de sinais de risco para inici. do vínculo de disposítivo'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.1.0', 'Jornada sem Redirecionamento', 'Indisponibilidade'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.1.0', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para a criação de cred. FIDO02'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.1.0', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para autenticação FIDO2'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.1.0', 'Jornada sem Redirecionamento', 'Outros'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.1.0', 'Jornada sem Redirecionamento', 'Revogação ou rejeição do vínculo de conta'),
  ('Serviços - Fase 3', '2.1.0', 'Vínculo de Dispositivo', 'Serviços - Fase 3 - Vínculo de Dispositivo'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.2.0', 'Jornada sem Redirecionamento', 'Associação de credencial FIDO2 ao vínculo de conta'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.2.0', 'Jornada sem Redirecionamento', 'Autorização de um consentimento de pagamento de JSR'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.2.0', 'Jornada sem Redirecionamento', 'Consulta de vínculo de conta'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.2.0', 'Jornada sem Redirecionamento', 'Criação de vínculo de conta'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.2.0', 'Jornada sem Redirecionamento', 'Envio de sinais de risco para inici. do vínculo de disposítivo'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.2.0', 'Jornada sem Redirecionamento', 'Indisponibilidade'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.2.0', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para a criação de cred. FIDO02'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.2.0', 'Jornada sem Redirecionamento', 'Obtenção de parâmetros para autenticação FIDO2'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.2.0', 'Jornada sem Redirecionamento', 'Outros'),
  ('Serviços - Fase 3 - Vínculo de Dispositivo', '2.2.0', 'Jornada sem Redirecionamento', 'Revogação ou rejeição do vínculo de conta'),
  ('Serviços - Fase 3', '2.2.0', 'Vínculo de Dispositivo', 'Serviços - Fase 3 - Vínculo de Dispositivo'),
  ('Serviços - Fase 3', '1.0.0-beta1.0', 'Webhook', 'Serviços - Fase 3 - Webhook'),
  ('Serviços - Fase 3', 'Não se Aplica', 'Webhook', 'Serviços - Fase 3 - Webhook'),
  ('Serviços - Fase 3', '1.2.0', 'Webhook', 'Serviços - Fase 3 - Webhook'),
  ('Serviços - Fase 3', '1.0.0-rc1.0', 'Webhook', 'Serviços - Fase 3 - Webhook'),
  ('Serviços - Fase 3', '1.0.0', 'Webhook', 'Serviços - Fase 3 - Webhook'),
  ('Serviços - Fase 3', '1.1.0', 'Webhook', 'Serviços - Fase 3 - Webhook'),
  ('Serviços - Fase 3', '1.3.0', 'Webhook', 'Serviços - Fase 3 - Webhook'),
  ('Portabilidade de Crédito', '1.0.0-beta.3', 'Não se Aplica', 'Portabilidade de Crédito - Não se Aplica'),
  ('Portabilidade de Crédito', '1.0.0-beta.3', 'CPC', 'Portabilidade de Crédito - CPC'),
  ('Portabilidade de Crédito', '1.0.0-beta.3', 'CPC', 'Efetivação da portabilidade'),
  ('Portabilidade de Crédito', '1.0.0-beta.3', 'CPC', 'Confirmação do Recebimento do Pagamento'),
  ('Portabilidade de Crédito', '1.0.0-beta.3', 'CPC', 'Espera da Liquidação'),
  ('Portabilidade de Crédito', '1.0.0-beta.3', 'CPC', 'Contraproposta (opcional)'),
  ('Portabilidade de Crédito', '1.0.0-beta.3', 'CPC', 'Iniciação da transferência'),
  ('Portabilidade de Crédito', '1.0.0-beta.2', 'CPC', 'Portabilidade de Crédito - CPC'),
  ('Portabilidade de Crédito', '1.0.0-beta.2', 'CPC', 'Efetivação da portabilidade'),
  ('Portabilidade de Crédito', '1.0.0-beta.2', 'CPC', 'Confirmação do Recebimento do Pagamento'),
  ('Portabilidade de Crédito', '1.0.0-beta.2', 'CPC', 'Espera da Liquidação'),
  ('Portabilidade de Crédito', '1.0.0-beta.2', 'CPC', 'Contraproposta (opcional)'),
  ('Portabilidade de Crédito', '1.0.0-beta.2', 'CPC', 'Iniciação da transferência'),
  ('Portabilidade de Crédito', '1.0.0', 'Não se Aplica', 'Portabilidade de Crédito - Não se Aplica'),
  ('Portabilidade de Crédito', '1.0.0', 'CPC', 'Portabilidade de Crédito - CPC'),
  ('Portabilidade de Crédito', '1.0.0', 'CPC', 'Efetivação da portabilidade'),
  ('Portabilidade de Crédito', '1.0.0', 'CPC', 'Confirmação do Recebimento do Pagamento'),
  ('Portabilidade de Crédito', '1.0.0', 'CPC', 'Espera da Liquidação'),
  ('Portabilidade de Crédito', '1.0.0', 'CPC', 'Contraproposta (opcional)'),
  ('Portabilidade de Crédito', '1.0.0', 'CPC', 'Iniciação da transferência'),
  ('Portabilidade de Crédito', '1.0.0-beta.1', 'Consignado Federal', 'Portabilidade de Crédito - Consignado Federal'),
  ('Portabilidade de Crédito', 'Não se Aplica', 'Consignado Federal', 'Portabilidade de Crédito - Consignado Federal')
ON CONFLICT (api_name_version, api_version, product_feature, stage_name_version) DO NOTHING;