INSERT INTO category_templates (
  id,
  category_name,
  sub_category_name,
  third_level_category_name,
  template_id,
  type
) VALUES
  (564,  'Conformidade',                          'Correções Necessárias em APIs',                  'Correções Necessárias em APIs',                               8794,  1),
  (626,  'Conformidade',                          'Ferramenta de Validação em Produção',            'FVP Manual - Testes Restritos',                               83331, 1),
  (620,  'Erro na Jornada ou Dados',              'Consentimento em Status Intermediário',           'Consentimento em Status Intermediário',                        68762, 1),
  (555,  'Erro na Jornada ou Dados',              'Consumindo os Dados',                            'Consumir APIs de Negócios',                                   123328, 1),
  (554,  'Erro na Jornada ou Dados',              'Consumindo os Dados',                            'Consumir APIs Resources',                                     123328, 1),
  (553,  'Erro na Jornada ou Dados',              'Consumindo os Dados',                            'Troca de Refresh Token por Access Token',                      123330, 1),
  (584,  'Erro na Jornada ou Dados',              'Fornecendo os Dados',                            'Fornecendo os Dados',                                         123333, 1),
  (605,  'Erro na Jornada ou Dados',              'Gerando uma Credencial',                         'Criar',                                                       164790, 1),
  (606,  'Erro na Jornada ou Dados',              'Gerando uma Credencial',                         'Deletar',                                                     164792, 1),
  (608,  'Erro na Jornada ou Dados',              'Gerando uma Credencial',                         'Desdobramentos',                                              164790, 1),
  (607,  'Erro na Jornada ou Dados',              'Gerando uma Credencial',                         'Recuperar',                                                   164793, 1),
  (545,  'Erro na Jornada ou Dados',              'Gerenciando a Credencial',                       'Criar',                                                       123327, 1),
  (546,  'Erro na Jornada ou Dados',              'Gerenciando a Credencial',                       'Modificar',                                                   123328, 1),
  (567,  'Erro na Jornada ou Dados',              'Gerenciando a Credencial',                       'Recuperar',                                                   68751, 1),
  (565,  'Erro na Jornada ou Dados',              'Gerenciando um Consentimento',                   'Revogando um Consentimento',                                  123328, 1),
  (570,  'Erro na Jornada ou Dados',              'Jornada do Usuário',                             'Jornada do Usuário',                                          68760, 1),
  (549,  'Erro na Jornada ou Dados',              'Obtendo um Consentimento',                       'Autenticação do Usuário',                                     68753, 1),
  (550,  'Erro na Jornada ou Dados',              'Obtendo um Consentimento',                       'Autorização pelo Usuário',                                    68753, 1),
  (547,  'Erro na Jornada ou Dados',              'Obtendo um Consentimento',                       'Criação de Consentimento',                                    123328, 1),
  (548,  'Erro na Jornada ou Dados',              'Obtendo um Consentimento',                       'Redirecionamento para Autenticação',                           68753, 1),
  (551,  'Erro na Jornada ou Dados',              'Obtendo um Consentimento',                       'Redirecionamento para Conclusão',                              68754, 1),
  (552,  'Erro na Jornada ou Dados',              'Obtendo um Consentimento',                       'Troca de AuthCode por AccesToken',                            123330, 1),
  (621,  'Erro na Jornada ou Dados',              'Pagamentos em Status Intermediário',             'Pagamentos em Status Intermediário',                           68763, 1),
  (566,  'Erro na Jornada ou Dados',              'Realizando o Pagamento',                         'Iniciando o Pagamento ou Solicitando Status',                  123328, 1),
  (556,  'Erro na Jornada ou Dados',              'Trabalhando os Dados',                           'Trabalhando os Dados',                                        123331, 1),
  (495,  'Incidentes',                            'APIs',                                           'Indisponibilidade',                                           68750, 1),
  (493,  'Incidentes',                            'APIs',                                           'Lentidão ou degradação',                                      68750, 1),
  (572,  'Incidentes',                            'APIs de Dados Abertos',                          'Erro',                                                        12040, 1),
  (574,  'Incidentes',                            'APIs de Dados Abertos',                          'Indisponibilidade',                                           12040, 1),
  (573,  'Incidentes',                            'APIs de Dados Abertos',                          'Lentidão ou Degradação',                                      12040, 1),
  (541,  'Incidentes',                            'Diretório',                                      'Certificados',                                                6752,  1),
  (491,  'Incidentes',                            'Diretório',                                      'Erro',                                                        20,    1),
  (492,  'Incidentes',                            'Diretório',                                      'Indisponibilidade',                                           20,    1),
  (490,  'Incidentes',                            'Diretório',                                      'Lentidão ou degradação',                                      20,    1),
  (575,  'Incidentes',                            'Ferramenta de Validação em Produção',            'Erro',                                                        12560, 1),
  (525,  'Incidentes',                            'Motor de Conformidade',                          'Erro',                                                        60736, 1),
  (526,  'Incidentes',                            'Motor de Conformidade',                          'Indisponibilidade',                                           60736, 1),
  (524,  'Incidentes',                            'Motor de Conformidade',                          'Lentidão ou Degradação',                                      60736, 1),
  (597,  'Incidentes',                            'Motor de Qualidade de Dados',                    'Erro',                                                        83830, 1),
  (598,  'Incidentes',                            'Motor de Qualidade de Dados',                    'Indisponibilidade',                                           83830, 1),
  (599,  'Incidentes',                            'Motor de Qualidade de Dados',                    'Lentidão ou Degradação',                                      83830, 1),
  (610,  'Incidentes',                            'Plataforma de Coleta de Métricas',               'Anomalia em API de Negócio',                                  60749, 1),
  (580,  'Incidentes',                            'Plataforma de Coleta de Métricas',               'Erro',                                                        20,    1),
  (602,  'Incidentes',                            'Plataforma de Coleta de Métricas',               'Erros de Desconformidade de Implementação',                   20,    1),
  (582,  'Incidentes',                            'Plataforma de Coleta de Métricas',               'Indisponibilidade',                                           20,    1),
  (581,  'Incidentes',                            'Plataforma de Coleta de Métricas',               'Lentidão ou Degradação',                                      20,    1),
  (518,  'Incidentes',                            'Plataforma de Disputas',                         'Erro',                                                        20,    1),
  (519,  'Incidentes',                            'Plataforma de Disputas',                         'Indisponibilidade',                                           20,    1),
  (517,  'Incidentes',                            'Plataforma de Disputas',                         'Lentidão ou Degradação',                                      20,    1),
  (500,  'Incidentes',                            'Portal Open Finance',                            'erro',                                                        20,    1),
  (501,  'Incidentes',                            'Portal Open Finance',                            'Indisponibilidade',                                           20,    1),
  (499,  'Incidentes',                            'Portal Open Finance',                            'Lentidão ou degradação',                                      20,    1),
  (515,  'Incidentes',                            'Ressarcimento',                                  'Erro',                                                        20,    1),
  (516,  'Incidentes',                            'Ressarcimento',                                  'Indisponibilidade',                                           20,    1),
  (514,  'Incidentes',                            'Ressarcimento',                                  'Lentidão ou Degradação',                                      20,    1),
  (531,  'Incidentes',                            'Segurança da Informação',                        'Notificação',                                                 20,    1),
  (496,  'Incidentes',                            'Service Desk',                                   'erro',                                                        20,    1),
  (498,  'Incidentes',                            'Service Desk',                                   'Indisponibilidade',                                           20,    1),
  (497,  'Incidentes',                            'Service Desk',                                   'Lentidão ou Degradação',                                      20,    1),
  (629,  'Incidentes',                            'Observabilidade',                                'Erro',                                                        20,    1),
  (630,  'Incidentes',                            'Observabilidade',                                'Indisponibilidade',                                           20,    1),
  (585,  'Indisponibilidade Não Programada',      'Notificação',                                    'Notificação',                                                 21367, 1),
  (487,  'Indisponibilidade Programada',          'Notificação',                                    'Notificação',                                                 386,   1),
  (502,  'Indisponibilidade Programada',          'Service Desk',                                   'Service Desk',                                                386,   1),
  (592,  'Monitoração e Gestão de Consequência',  'Abertos pela Estrutura',                         'Descumprimento de SLA',                                       31457, 10),
  (614,  'Monitoração e Gestão de Consequência',  'Desconformidades',                               'Análise de Desconformidades',                                 46167, 10),
  (615,  'Monitoração e Gestão de Consequência',  'Desconformidades',                               'Apresentação Avaliação Específica de Taxa de Conversão',      65878, 10),
  (616,  'Monitoração e Gestão de Consequência',  'Desconformidades',                               'Apresentação do Plano de Adequação',                          56975, 10),
  (617,  'Monitoração e Gestão de Consequência',  'Desconformidades',                               'Diagnóstico de Taxa de Conversão',                            56975, 10),
  (618,  'Monitoração e Gestão de Consequência',  'Desconformidades',                               'Apresentação Relatório de Situações de Desconformidade',      65878, 10),
  (612,  'Monitoração e Gestão de Consequência',  'Desconformidades',                               'Painel - Informações',                                        12,    10),
  (613,  'Monitoração e Gestão de Consequência',  'Desconformidades',                               'Painel - Melhorias',                                          12,    10),
  (586,  'Monitoração e Gestão de Consequência',  'Ferramenta de Validação em Produção',            'Descumprimento de SLA',                                       25439, 10),
  (595,  'Monitoração e Gestão de Consequência',  'FVP 1.0',                                        'Descumprimento de Certificação de Segurança',                 25439, 10),
  (594,  'Monitoração e Gestão de Consequência',  'FVP Cadastral',                                  'Cadastro Incorreto no Diretório',                             25439, 10),
  (603,  'Monitoração e Gestão de Consequência',  'Jornada UX',                                     'Descumprimento Ditame Regulatório',                           25439, 10),
  (609,  'Monitoração e Gestão de Consequência',  'Jornada UX',                                     'Informação',                                                  33360, 10),
  (596,  'Monitoração e Gestão de Consequência',  'Processo de Onboarding',                         'Não Iniciado',                                                33360, 10),
  (587,  'Monitoração e Gestão de Consequência',  'Tickets Bilaterais',                             'Descumprimento de SLA',                                       31459, 10),
  (604,  'Notificação',                           'Ferramenta de Validação em Produção',            'Testes de Homologação',                                       52419, 10),
  (622,  'Notificação',                           'Motor de Qualidade de Dados',                    'Não Envio de Reporte D+1',                                    83832, 10),
  (611,  'Notificação',                           'Plataforma de Coleta de Métricas',               'Não Envio de Reporte até 08 de D+1',                          52419, 10),
  (636,  'Notificação',                           'Jornada UX',                                     'Informação',                                                  52419, 10),
  (536,  'Processo de Onboarding',                'Comunicação de Conclusão de Onboarding',         'Conclusão de Onboarding',                                     5614,  10),
  (535,  'Processo de Onboarding',                'Solicitação de Interesse em Participação',       'Consumidora de Dados e Serviços',                             87673, 10),
  (534,  'Processo de Onboarding',                'Solicitação de Interesse em Participação',       'Detentora',                                                   5611,  10),
  (533,  'Processo de Onboarding',                'Solicitação de Interesse em Participação',       'Iniciadora',                                                  64015, 10),
  (593,  'Requisição',                            'Reexecução',                                     'FVP 1.0',                                                     32268, 10),
  (619,  'Requisição',                            'Reexecução',                                     'FVP Manual - Testes Restritos',                               46808, 10),
  (623,  'Requisição',                            'Reexecução',                                     'Jornada UX',                                                  55563, 10),
  (625,  'Requisição',                            'Contestação',                                    'FVP Manual - Testes Restritos',                               63996, 10),
  (632,  'Gestão de Cadastro',                    'Cadastro de Nova Instituição',                   'Cadastro',                                                    82402, 10),
  (633,  'Gestão de Cadastro',                    'Exclusão de Instituição',                        'Exclusão',                                                    12,    10),
  (634,  'Gestão de Cadastro',                    'Exclusão de Papel Regulatório (Role)',           'Exclusão',                                                    12,    10),
  (590,  'Solicitação de acesso',                 'Acompanhamento de Certificação',                 'Concessão de Acesso',                                         25523, 10),
  (591,  'Solicitação de acesso',                 'Acompanhamento de Certificação',                 'Revogação de Acesso',                                         25525, 10),
  (505,  'Solicitação de acesso',                 'Diretório',                                      'Concessão',                                                   12,    10),
  (506,  'Solicitação de acesso',                 'Diretório',                                      'Revogação',                                                   12,    10),
  (527,  'Solicitação de acesso',                 'MISP',                                           'Concessão - Instância',                                       12,    10),
  (528,  'Solicitação de acesso',                 'MISP',                                           'Concessão - Usuário',                                         12,    10),
  (529,  'Solicitação de acesso',                 'MISP',                                           'Revogação - Instância',                                       12,    10),
  (530,  'Solicitação de acesso',                 'MISP',                                           'Revogação - Usuário',                                         12,    10),
  (557,  'Solicitação de acesso',                 'Painel de Indicadores',                          'Concessão de Acesso',                                         8986,  10),
  (558,  'Solicitação de acesso',                 'Painel de Indicadores',                          'Revogação de Acesso',                                         8991,  10),
  (463,  'Solicitação de acesso',                 'Service Desk',                                   'Concessão Equipe N2',                                         43,    10),
  (259,  'Solicitação de acesso',                 'Service Desk',                                   'Concessão Requisitante',                                      39,    10),
  (488,  'Solicitação de acesso',                 'Service Desk',                                   'Revogação Equipe N2',                                         789,   10),
  (489,  'Solicitação de acesso',                 'Service Desk',                                   'Revogação Requisitante',                                      12,    10),
  (513,  'Solicitação de certificados',           'Enviar pedido de certificação',                  'Certificado',                                                 74207, 10),
  (631,  'Solicitação de certificados',           'Enviar pedido de certificação',                  'Evidência de homologação no ambiente pix tester',             74194, 10),
  (483,  'Solicitação de Informações',            'APIs',                                           'Informações',                                                 60752, 10),
  (510,  'Solicitação de Informações',            'Conformidade',                                   'APIs',                                                        60753, 10),
  (576,  'Solicitação de Informações',            'Conformidade',                                   'Ferramenta de Validação em Produção',                         12561, 10),
  (511,  'Solicitação de Informações',            'Conformidade',                                   'Motor de conformidade',                                       12,    10),
  (512,  'Solicitação de Informações',            'Conformidade',                                   'Política de certificação',                                    12,    10),
  (624,  'Solicitação de Informações',            'Conformidade',                                   'Política de Conformidade',                                    12,    10),
  (481,  'Solicitação de Informações',            'Diretório',                                      'Informações',                                                 12,    10),
  (588,  'Solicitação de Informações',            'Envio de Manifestação',                          'Manifestação',                                                25625, 10),
  (600,  'Solicitação de Informações',            'Motor de Qualidade de Dados',                    'Informações',                                                 83831, 10),
  (579,  'Solicitação de Informações',            'Plataforma de Coleta de Métricas',               'Plataforma de Coleta de Métricas',                            12,    10),
  (520,  'Solicitação de Informações',            'Plataforma de Disputas',                         'Disputas',                                                    12,    10),
  (521,  'Solicitação de Informações',            'Ressarcimento',                                  'Ressarcimento',                                               12,    10),
  (482,  'Solicitação de Informações',            'Service Desk',                                   'Informações',                                                 12,    10),
  (627,  'Solicitação de Informações',            'Observabilidade',                                'Informações',                                                 12,    10),
  (485,  'Solicitação de Melhorias',              'APIs',                                           'Melhorias',                                                   60752, 10),
  (484,  'Solicitação de Melhorias',              'Diretório',                                      'Melhorias',                                                   12,    10),
  (577,  'Solicitação de Melhorias',              'Ferramenta de Validação em Produção',            'Melhorias',                                                   12561, 10),
  (568,  'Solicitação de Melhorias',              'Guia de Experiência',                            'Guia de Experiência',                                         60754, 10),
  (569,  'Solicitação de Melhorias',              'Jornada do Usuário',                             'Jornada do Usuário',                                          60754, 10),
  (540,  'Solicitação de Melhorias',              'Motor de Conformidade',                          'Melhorias',                                                   6753,  10),
  (601,  'Solicitação de Melhorias',              'Motor de Qualidade de Dados',                    'Melhorias',                                                   83831, 10),
  (583,  'Solicitação de Melhorias',              'Plataforma de Coleta de Métricas',               'Plataforma de Coleta de Métricas',                            12,    10),
  (522,  'Solicitação de Melhorias',              'Plataforma de Disputas',                         'Disputas',                                                    12,    10),
  (523,  'Solicitação de Melhorias',              'Ressarcimento',                                  'Ressarcimento',                                               12,    10),
  (486,  'Solicitação de Melhorias',              'Service Desk',                                   'Melhorias',                                                   12,    10),
  (628,  'Solicitação de Melhorias',              'Observabilidade',                                'Melhorias',                                                   12,    10)
ON CONFLICT (id) DO UPDATE
SET
  category_name              = EXCLUDED.category_name,
  sub_category_name          = EXCLUDED.sub_category_name,
  third_level_category_name  = EXCLUDED.third_level_category_name,
  template_id                = EXCLUDED.template_id,
  type                       = EXCLUDED.type;
