INSERT INTO category_templates (
  id,
  category_name,
  sub_category_name,
  third_level_category_name,
  template_id,
  type
) VALUES
  (564,  'Conformidade',                          'Correções Necessárias em APIs',                  'Correções Necessárias em APIs',                               8794,  1),
  (626,  'Conformidade',                          'Ferramenta de Validação em Produção',            'FVP Manual - Testes Restritos',                               83331, 1),
  (620,  'Erro na Jornada ou Dados',              'Consentimento em Status Intermediário',           'Consentimento em Status Intermediário',                        68762, 1),
  (555,  'Erro na Jornada ou Dados',              'Consumindo os Dados',                            'Consumir APIs de Negócios',                                   123328, 1),
  (554,  'Erro na Jornada ou Dados',              'Consumindo os Dados',                            'Consumir APIs Resources',                                     123328, 1),
  (553,  'Erro na Jornada ou Dados',              'Consumindo os Dados',                            'Troca de Refresh Token por Access Token',                      123330, 1),
  (584,  'Erro na Jornada ou Dados',              'Fornecendo os Dados',                            'Fornecendo os Dados',                                         123333, 1),
  (605,  'Erro na Jornada ou Dados',              'Gerando uma Credencial',                         'Criar',                                                       164790, 1),
  (606,  'Erro na Jornada ou Dados',              'Gerando uma Credencial',                         'Deletar',                                                     164792, 1),
  (608,  'Erro na Jornada ou Dados',              'Gerando uma Credencial',                         'Desdobramentos',                                              164790, 1),
  (607,  'Erro na Jornada ou Dados',              'Gerando uma Credencial',                         'Recuperar',                                                   164793, 1),
  (545,  'Erro na Jornada ou Dados',              'Gerenciando a Credencial',                       'Criar',                                                       123327, 1),
  (546,  'Erro na Jornada ou Dados',              'Gerenciando a Credencial',                       'Modificar',                                                   123328, 1),
  (567,  'Erro na Jornada ou Dados',              'Gerenciando a Credencial',                       'Recuperar',                                                   68751, 1),
  (565,  'Erro na Jornada ou Dados',              'Gerenciando um Consentimento',                   'Revogando um Consentimento',                                  123328, 1),
  (570,  'Erro na Jornada ou Dados',              'Jornada do Usuário',                             'Jornada do Usuário',                                          68760, 1),
  (549,  'Erro na Jornada ou Dados',              'Obtendo um Consentimento',                       'Autenticação do Usuário',                                     68753, 1),
  (550,  'Erro na Jornada ou Dados',              'Obtendo um Consentimento',                       'Autorização pelo Usuário',                                    68753, 1),
  (547,  'Erro na Jornada ou Dados',              'Obtendo um Consentimento',                       'Criação de Consentimento',                                    123328, 1),
  (548,  'Erro na Jornada ou Dados',              'Obtendo um Consentimento',                       'Redirecionamento para Autenticação',                           68753, 1),
  (551,  'Erro na Jornada ou Dados',              'Obtendo um Consentimento',                       'Redirecionamento para Conclusão',                              68754, 1),
  (552,  'Erro na Jornada ou Dados',              'Obtendo um Consentimento',                       'Troca de AuthCode por AccesToken',                            123330, 1),
  (621,  'Erro na Jornada ou Dados',              'Pagamentos em Status Intermediário',             'Pagamentos em Status Intermediário',                           68763, 1),
  (566,  'Erro na Jornada ou Dados',              'Realizando o Pagamento',                         'Iniciando o Pagamento ou Solicitando Status',                  123328, 1),
  (556,  'Erro na Jornada ou Dados',              'Trabalhando os Dados',                           'Trabalhando os Dados',                                        123331, 1),
  (495,  'Incidentes',                            'APIs',                                           'Indisponibilidade',                                           68750, 1),
  (493,  'Incidentes',                            'APIs',                                           'Lentidão ou degradação',                                      68750, 1),
  (572,  'Incidentes',                            'APIs de Dados Abertos',                          'Erro',                                                        12040, 1),
  (574,  'Incidentes',                            'APIs de Dados Abertos',                          'Indisponibilidade',                                           12040, 1),
  (573,  'Incidentes',                            'APIs de Dados Abertos',                          'Lentidão ou Degradação',                                      12040, 1),
  (541,  'Incidentes',                            'Diretório',                                      'Certificados',                                                6752,  1),
  (491,  'Incidentes',                            'Diretório',                                      'Erro',                                                        20,    1),
  (492,  'Incidentes',                            'Diretório',                                      'Indisponibilidade',                                           20,    1),
  (490,  'Incidentes',                            'Diretório',                                      'Lentidão ou degradação',                                      20,    1),
  (575,  'Incidentes',                            'Ferramenta de Validação em Produção',            'Erro',                                                        12560, 1),
  (525,  'Incidentes',                            'Motor de Conformidade',                          'Erro',                                                        60736, 1),
  (526,  'Incidentes',                            'Motor de Conformidade',                          'Indisponibilidade',                                           60736, 1),
  (524,  'Incidentes',                            'Motor de Conformidade',                          'Lentidão ou Degradação',                                      60736, 1),
  (597,  'Incidentes',                            'Motor de Qualidade de Dados',                    'Erro',                                                        83830, 1),
  (598,  'Incidentes',                            'Motor de Qualidade de Dados',                    'Indisponibilidade',                                           83830, 1),
  (599,  'Incidentes',                            'Motor de Qualidade de Dados',                    'Lentidão ou Degradação',                                      83830, 1),
  (610,  'Incidentes',                            'Plataforma de Coleta de Métricas',               'Anomalia em API de Negócio',                                  60749, 1),
  (580,  'Incidentes',                            'Plataforma de Coleta de Métricas',               'Erro',                                                        20,    1),
  (602,  'Incidentes',                            'Plataforma de Coleta de Métricas',               'Erros de Desconformidade de Implementação',                   20,    1),
  (582,  'Incidentes',                            'Plataforma de Coleta de Métricas',               'Indisponibilidade',                                           20,    1),
  (581,  'Incidentes',                            'Plataforma de Coleta de Métricas',               'Lentidão ou Degradação',                                      20,    1),
  (518,  'Incidentes',                            'Plataforma de Disputas',                         'Erro',                                                        20,    1),
  (519,  'Incidentes',                            'Plataforma de Disputas',                         'Indisponibilidade',                                           20,    1),
  (517,  'Incidentes',                            'Plataforma de Disputas',                         'Lentidão ou Degradação',                                      20,    1),
  (500,  'Incidentes',                            'Portal Open Finance',                            'erro',                                                        20,    1),
  (501,  'Incidentes',                            'Portal Open Finance',                            'Indisponibilidade',                                           20,    1),
  (499,  'Incidentes',                            'Portal Open Finance',                            'Lentidão ou degradação',                                      20,    1),
  (515,  'Incidentes',                            'Ressarcimento',                                  'Erro',                                                        20,    1),
  (516,  'Incidentes',                            'Ressarcimento',                                  'Indisponibilidade',                                           20,    1),
  (514,  'Incidentes',                            'Ressarcimento',                                  'Lentidão ou Degradação',                                      20,    1),
  (531,  'Incidentes',                            'Segurança da Informação',                        'Notificação',                                                 20,    1),
  (496,  'Incidentes',                            'Service Desk',                                   'erro',                                                        20,    1),
  (498,  'Incidentes',                            'Service Desk',                                   'Indisponibilidade',                                           20,    1),
  (497,  'Incidentes',                            'Service Desk',                                   'Lentidão ou Degradação',                                      20,    1),
  (629,  'Incidentes',                            'Observabilidade',                                'Erro',                                                        20,    1),
  (630,  'Incidentes',                            'Observabilidade',                                'Indisponibilidade',                                           20,    1),
  (585,  'Indisponibilidade Não Programada',      'Notificação',                                    'Notificação',                                                 21367, 1),
  (487,  'Indisponibilidade Programada',          'Notificação',                                    'Notificação',                                                 386,   1),
  (502,  'Indisponibilidade Programada',          'Service Desk',                                   'Service Desk',                                                386,   1),
  (463,  'Solicitação de acesso',                 'Service Desk',                                   'Concessão Equipe N2',                                         43,    10),
  (259,  'Solicitação de acesso',                 'Service Desk',                                   'Concessão Requisitante',                                      39,    10),
  (488,  'Solicitação de acesso',                 'Service Desk',                                   'Revogação Equipe N2',                                         789,   10),
ON CONFLICT (id) DO UPDATE
SET
  category_name              = EXCLUDED.category_name,
  sub_category_name          = EXCLUDED.sub_category_name,
  third_level_category_name  = EXCLUDED.third_level_category_name,
  template_id                = EXCLUDED.template_id,
  type                       = EXCLUDED.type;
