INSERT INTO template_fields (
  template_id,
  field_name,
  field_label_api,
  field_type,
  is_required,
  context_key,
  list_options
) VALUES
  (123328, 'Seu client_id neste participante',           'CustomColumn72sr',  'text',              TRUE, 'client_id',             NULL),
  (123328, 'URL do endpoint acionado',                   'CustomColumn68sr',  'long',              TRUE, 'endpoint',              NULL),
  (123328, 'Headers e Payload da solicitação (Request)', 'CustomColumn69sr',  'long',              TRUE, 'payload_request',       NULL),
  (123328, 'Código HTTP da resposta',                    'CustomColumn229sr', 'list',              TRUE, 'http_status_code',      '{"429":"2","5xx":"4","4xx":"3","*":"1"}'),
  (123328, 'Headers e Payload da resposta (Response)',   'CustomColumn71sr',  'long',              TRUE, 'payload_response',      NULL),
  (123328, 'Nome e Versão da API',                       'CustomColumn114sr', 'text',              TRUE, 'stage_name_version',      NULL),
  (123328, 'Versão API',                                 'CustomColumn115sr', 'text',              TRUE, 'api_version',           NULL),
  (123328, 'Produto/Funcionalidade',                     'CustomColumn165sr', 'text',              TRUE, 'product_feature',       NULL),
  (123328, 'Tipo do Cliente',                            'CustomColumn120sr', 'list_multi_select', TRUE, 'tipo_cliente',          '{"PF":"1","PJ":"2"}'),
  (123328, 'Canal da Jornada',                           'CustomColumn174sr', 'list',              TRUE, 'canal_jornada',         '{"App to app":"1","App to browser":"2","Browser to browser":"3","Browser to app":"4","Não se aplica":"5"}'),
  (123328, 'X-Fapi-Interaction-ID',                      'CustomColumn156sr', 'long',              TRUE, 'x_fapi_interaction_id', NULL),
  (123328, 'Destinatário',                               'CustomColumn38sr',  'text',              TRUE, 'destinatario',          NULL),
  (12040, 'API de Dados Abertos', 'CustomColumn95sr', 'list', TRUE, 'api_dados_abertos', NULL),
  (12560, 'Número do ticket gerado pela FVP', 'CustomColumn99sr', 'text', TRUE, 'fvp_ticket_number', NULL),
  (21367, 'Destinatário',                                          'CustomColumn38sr',  'text',              FALSE, 'destinatario',       NULL),
  (21367, 'Este problema ocorreu no processo de Onboarding de ITP ?', 'CustomColumn59sr', 'text',            FALSE, 'onboarding_itp',     NULL),
  (21367, 'Nome e Versão da API',                                  'CustomColumn114sr', 'text',              TRUE, 'stage_name_version',   NULL),
  (21367, 'Versão API',                                            'CustomColumn115sr', 'text',              TRUE,  'api_version',        NULL),
  (21367, 'Produto/Funcionalidade',                                'CustomColumn165sr', 'text',              TRUE,  'product_feature',    NULL),
  (21367, 'Etapa(nome e versão api)',                              'CustomColumn166sr', 'text',              TRUE,  'stage_name_version', NULL),
  (21367, 'Tipo do Cliente',                                       'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente',       '{"PF":"1","PJ":"2"}'),
  (386, 'Indisponibilidade - Inicio', 'CustomColumn22sr', 'datetime', TRUE, 'indisponibilidade_inicio', NULL),
  (386, 'Indisponibilidade - Fim',    'CustomColumn23sr', 'datetime', TRUE, 'indisponibilidade_fim',    NULL),
  (39, 'Nome Completo do novo usuário', 'CustomColumn6sr',  'text', TRUE,  'nome_completo_usuario', NULL),
  (39, 'E-mail do novo usuário',        'CustomColumn7sr',  'text', TRUE,  'email_usuario',         NULL),
  (39, 'Fone para contato',             'CustomColumn8sr',  'text', TRUE,  'fone_contato',          NULL),
  (39, 'Nome da instituição',           'CustomColumn9sr',  'text', TRUE,  'nome_instituicao',      NULL),
  (39, 'Setor econômico',               'CustomColumn10sr', 'list', TRUE,  'setor_economico',       NULL),
  (43, 'Nome da instituição',    'CustomColumn9sr',  'text', TRUE,  'nome_instituicao',  NULL),
  (43, 'E-mail para notificação','CustomColumn12sr', 'text', FALSE, 'email_notificacao', NULL),
  (43, 'E-mail do responsável',  'CustomColumn14sr', 'text', TRUE,  'email_responsavel', NULL),
  (43, 'Fone para contato',      'CustomColumn8sr',  'text', TRUE,  'fone_contato',      NULL),
  (43, 'Analista, e-mail, fone', 'CustomColumn15sr', 'long', TRUE,  'analista_email_fone', NULL),
  (60735, 'Destinatário',                                          'CustomColumn38sr',  'text',              FALSE, 'destinatario',       NULL),
  (60735, 'Este problema ocorreu no processo de Onboarding de ITP ?', 'CustomColumn59sr', 'text',            FALSE, 'onboarding_itp',     NULL),
  (60735, 'Nome e Versão da API',                                  'CustomColumn114sr', 'text',              TRUE, 'stage_name_version',   NULL),
  (60735, 'Versão API',                                            'CustomColumn115sr', 'text',              TRUE,  'api_version',        NULL),
  (60735, 'Produto/Funcionalidade',                                'CustomColumn165sr', 'text',              TRUE,  'product_feature',    NULL),
  (60735, 'Etapa(nome e versão api)',                              'CustomColumn166sr', 'text',              TRUE,  'stage_name_version', NULL),
  (60735, 'Tipo do Cliente',                                       'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente',       '{"PF":"1","PJ":"2"}'),
  (60736, 'Nome e Versão da API',                              'CustomColumn114sr', 'text',              TRUE, 'stage_name_version',   NULL),
  (60736, 'Versão API',                                        'CustomColumn115sr', 'text',              TRUE,  'api_version',        NULL),
  (60736, 'Produto/Funcionalidade',                            'CustomColumn165sr', 'text',              TRUE,  'product_feature',    NULL),
  (60736, 'Etapa(nome e versão api)',                          'CustomColumn166sr', 'text',              TRUE,  'stage_name_version', NULL),
  (60736, 'Tipo do Cliente',                                   'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente',       '{"PF":"1","PJ":"2"}'),
  (60736, 'Test Plan ID onde foi observado o incidente',       'CustomColumn37sr',  'text',              TRUE,  'test_plan_id',       NULL),
  (60737, 'Destinatário',                                          'CustomColumn38sr',  'text',              FALSE, 'destinatario',       NULL),
  (60737, 'Este problema ocorreu no processo de Onboarding de ITP ?', 'CustomColumn59sr', 'text',            FALSE, 'onboarding_itp',     NULL),
  (60737, 'Nome e Versão da API',                                  'CustomColumn114sr', 'text',              TRUE, 'stage_name_version',   NULL),
  (60737, 'Versão API',                                            'CustomColumn115sr', 'text',              TRUE,  'api_version',        NULL),
  (60737, 'Produto/Funcionalidade',                                'CustomColumn165sr', 'text',              TRUE,  'product_feature',    NULL),
  (60737, 'Etapa(nome e versão api)',                              'CustomColumn166sr', 'text',              TRUE,  'stage_name_version', NULL),
  (60737, 'Tipo do Cliente',                                       'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente',       '{"PF":"1","PJ":"2"}'),
  (60738, 'Destinatário',                                  'CustomColumn38sr',  'text',              TRUE,  'destinatario',         NULL),
  (60738, 'Seu client_id nesta transmissora/detentora',    'CustomColumn79sr',  'text',              FALSE, 'client_id_transmissora', NULL),
  (60738, 'Nome e Versão da API',                          'CustomColumn114sr', 'text',              TRUE, 'stage_name_version',     NULL),
  (60738, 'Versão API',                                    'CustomColumn115sr', 'text',              TRUE,  'api_version',          NULL),
  (60738, 'Produto/Funcionalidade',                        'CustomColumn165sr', 'text',              TRUE,  'product_feature',      NULL),
  (60738, 'Etapa(nome e versão api)',                      'CustomColumn166sr', 'text',              TRUE,  'stage_name_version',   NULL),
  (60738, 'Tipo do Cliente',                               'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente',         '{"PF":"1","PJ":"2"}'),
  (60739, 'Destinatário',                                    'CustomColumn38sr',  'text',              TRUE,  'destinatario',       NULL),
  (60739, 'Seu client_id neste participante',                'CustomColumn72sr',  'text',              TRUE,  'client_id',          NULL),
  (60739, 'URL do endpoint acionado',                        'CustomColumn68sr',  'long',              TRUE,  'endpoint',           NULL),
  (60739, 'Headers e Payload da solicitação (Request)',      'CustomColumn69sr',  'long',              TRUE,  'payload_request',    NULL),
  (60739, 'Código HTTP da resposta',                         'CustomColumn229sr', 'list',              TRUE,  'http_status_code',   '{"429":"2","5xx":"4","4xx":"3","*":"1"}'),
  (60739, 'Headers e Payload da resposta (Response)',        'CustomColumn71sr',  'long',              TRUE,  'payload_response',   NULL),
  (60739, 'Nome e Versão da API',                            'CustomColumn114sr', 'text',              TRUE, 'stage_name_version',   NULL),
  (60739, 'Versão API',                                      'CustomColumn115sr', 'text',              TRUE,  'api_version',        NULL),
  (60739, 'Produto/Funcionalidade',                          'CustomColumn165sr', 'text',              TRUE,  'product_feature',    NULL),
  (60739, 'Etapa(nome e versão api)',                        'CustomColumn166sr', 'text',              TRUE,  'stage_name_version', NULL),
  (60739, 'Tipo do Cliente',                                 'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente',       '{"PF":"1","PJ":"2"}'),
  (60740, 'Destinatário',                                                    'CustomColumn38sr',  'text',              TRUE,  'destinatario',        NULL),
  (60740, 'Nome da marca de destino',                                        'CustomColumn73sr',  'text',              TRUE,  'nome_marca_destino',  NULL),
  (60740, 'URL do arquivo .well-known da transmissora/detentora',            'CustomColumn74sr',  'long',              TRUE,  'url_well_known',      NULL),
  (60740, 'Conteúdo do arquivo .well-known da transmissora/detentora',       'CustomColumn75sr',  'long',              TRUE,  'conteudo_well_known', NULL),
  (60740, 'Tipo do Cliente',                                                 'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente',        '{"PF":"1","PJ":"2"}'),
  (60740, 'Nome e Versão da API',                                            'CustomColumn114sr', 'text',              TRUE, 'stage_name_version',    NULL),
  (60740, 'Versão API',                                                      'CustomColumn115sr', 'text',              TRUE,  'api_version',         NULL),
  (60740, 'Produto/Funcionalidade',                                          'CustomColumn165sr', 'text',              TRUE,  'product_feature',     NULL),
  (60740, 'Etapa(nome e versão api)',                                        'CustomColumn166sr', 'text',              TRUE,  'stage_name_version',  NULL),
  (60741, 'Destinatário',                                              'CustomColumn38sr',  'text',              TRUE,  'destinatario',          NULL),
  (60741, 'Nome da marca transmissora/detentora',                      'CustomColumn76sr',  'text',              TRUE,  'nome_marca_transmissora', NULL),
  (60741, 'URL do arquivo .well-known da transmissora/detentora',      'CustomColumn74sr',  'long',              TRUE,  'url_well_known',        NULL),
  (60741, 'Conteúdo do arquivo .well-known da transmissora/detentora', 'CustomColumn75sr',  'long',              TRUE,  'conteudo_well_known',   NULL),
  (60741, 'URL para qual o usuário deveria voltar',                    'CustomColumn77sr',  'long',              TRUE,  'url_retorno_usuario',   NULL),
  (60741, 'SSA da sua aplicação',                                      'CustomColumn78sr',  'long',              TRUE,  'ssa_aplicacao',         NULL),
  (60741, 'Tipo do Cliente',                                           'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente',          '{"PF":"1","PJ":"2"}'),
  (60741, 'Nome e Versão da API',                                      'CustomColumn114sr', 'text',              TRUE, 'stage_name_version',      NULL),
  (60741, 'Versão API',                                                'CustomColumn115sr', 'text',              TRUE,  'api_version',           NULL),
  (60741, 'Produto/Funcionalidade',                                    'CustomColumn165sr', 'text',              TRUE,  'product_feature',       NULL),
  (60741, 'Etapa(nome e versão api)',                                  'CustomColumn166sr', 'text',              TRUE,  'stage_name_version',    NULL),
  (60742, 'Destinatário',                                              'CustomColumn38sr',  'text',              TRUE,  'destinatario',          NULL),
  (60742, 'Seu client_id nesta transmissora/receptora',                'CustomColumn79sr',  'text',              TRUE,  'client_id_transmissora', NULL),
  (60742, 'URL do endpoint acionado',                                  'CustomColumn68sr',  'long',              TRUE,  'endpoint',              NULL),
  (60742, 'Headers e Payload da solicitação (Request)',                'CustomColumn69sr',  'long',              TRUE,  'payload_request',       NULL),
  (60742, 'Código HTTP da resposta',                                   'CustomColumn229sr', 'list',              TRUE,  'http_status_code',      '{"429":"2","5xx":"4","4xx":"3","*":"1"}'),
  (60742, 'Headers e Payload da resposta (Response)',                  'CustomColumn71sr',  'long',              TRUE,  'payload_response',      NULL),
  (60742, 'URL do arquivo .well-known da transmissora/detentora',      'CustomColumn74sr',  'long',              TRUE,  'url_well_known',        NULL),
  (60742, 'Conteúdo do arquivo .well-known da transmissora/detentora', 'CustomColumn75sr',  'long',              TRUE,  'conteudo_well_known',   NULL),
  (60742, 'Tipo do Cliente',                                           'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente',          '{"PF":"1","PJ":"2"}'),
  (60742, 'Nome e Versão da API',                                      'CustomColumn114sr', 'text',              TRUE, 'stage_name_version',      NULL),
  (60742, 'Versão API',                                                'CustomColumn115sr', 'text',              TRUE,  'api_version',           NULL),
  (60742, 'Produto/Funcionalidade',                                    'CustomColumn165sr', 'text',              TRUE,  'product_feature',       NULL),
  (60742, 'Etapa(nome e versão api)',                                  'CustomColumn166sr', 'text',              TRUE,  'stage_name_version',    NULL),
  (60743, 'Destinatário',                               'CustomColumn38sr',  'text',              TRUE,  'destinatario',       NULL),
  (60743, 'URL do endpoint acionado',                   'CustomColumn68sr',  'long',              TRUE,  'endpoint',           NULL),
  (60743, 'Headers e Payload da solicitação (Request)', 'CustomColumn69sr',  'long',              TRUE,  'payload_request',    NULL),
  (60743, 'Código HTTP da resposta',                    'CustomColumn229sr', 'list',              TRUE,  'http_status_code',   '{"429":"2","5xx":"4","4xx":"3","*":"1"}'),
  (60743, 'Headers e Payload da resposta (Response)',   'CustomColumn71sr',  'long',              TRUE,  'payload_response',   NULL),
  (60743, 'Tipo do Cliente',                            'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente',       '{"PF":"1","PJ":"2"}'),
  (60743, 'Nome e Versão da API',                       'CustomColumn114sr', 'text',              TRUE, 'stage_name_version',   NULL),
  (60743, 'Versão API',                                 'CustomColumn115sr', 'text',              TRUE,  'api_version',        NULL),
  (60743, 'Produto/Funcionalidade',                     'CustomColumn165sr', 'text',              TRUE,  'product_feature',    NULL),
  (60743, 'Etapa(nome e versão api)',                   'CustomColumn166sr', 'text',              TRUE,  'stage_name_version', NULL),
  (60744, 'Destinatário',                               'CustomColumn38sr',  'text',              TRUE,  'destinatario',       NULL),
  (60744, 'URL do endpoint acionado',                   'CustomColumn68sr',  'long',              TRUE,  'endpoint',           NULL),
  (60744, 'Headers e Payload da solicitação (Request)', 'CustomColumn69sr',  'long',              FALSE, 'payload_request',    NULL),
  (60744, 'Código HTTP da resposta',                    'CustomColumn229sr', 'list',              TRUE,  'http_status_code',   '{"429":"2","5xx":"4","4xx":"3","*":"1"}'),
  (60744, 'Headers e Payload da resposta (Response)',   'CustomColumn71sr',  'long',              TRUE,  'payload_response',   NULL),
  (60744, 'Tipo do Cliente',                            'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente',       '{"PF":"1","PJ":"2"}'),
  (60744, 'Nome e Versão da API',                       'CustomColumn114sr', 'text',              TRUE, 'stage_name_version',   NULL),
  (60744, 'Versão API',                                 'CustomColumn115sr', 'text',              TRUE,  'api_version',        NULL),
  (60744, 'Produto/Funcionalidade',                     'CustomColumn165sr', 'text',              TRUE,  'product_feature',    NULL),
  (60744, 'Etapa(nome e versão api)',                   'CustomColumn166sr', 'text',              TRUE,  'stage_name_version', NULL),
  (60745, 'Destinatário',                                              'CustomColumn38sr',  'text',              TRUE,  'destinatario',       NULL),
  (60745, 'Indique a qual fase e etapa o problema está relacionado',   'CustomColumn93sr',  'list',              TRUE,  'fase_etapa',         NULL),
  (60745, 'Tipo do Cliente',                                           'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente',       '{"PF":"1","PJ":"2"}'),
  (60745, 'Nome e Versão da API',                                      'CustomColumn114sr', 'text',              TRUE, 'stage_name_version',   NULL),
  (60745, 'Versão API',                                                'CustomColumn115sr', 'text',              TRUE,  'api_version',        NULL),
  (60745, 'Produto/Funcionalidade',                                    'CustomColumn165sr', 'text',              TRUE,  'product_feature',    NULL),
  (60745, 'Etapa(nome e versão api)',                                  'CustomColumn166sr', 'text',              TRUE,  'stage_name_version', NULL),
  (60748, 'Destinatário',              'CustomColumn38sr',  'text',              TRUE,  'destinatario',       NULL),
  (60748, 'URL do endpoint acionado',  'CustomColumn68sr',  'long',              TRUE,  'endpoint',           NULL),
  (60748, 'Código HTTP da resposta',   'CustomColumn229sr', 'list',              TRUE,  'http_status_code',   '{"429":"2","5xx":"4","4xx":"3","*":"1"}'),
  (60748, 'Tipo do Cliente',           'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente',       '{"PF":"1","PJ":"2"}'),
  (60748, 'Nome e Versão da API',      'CustomColumn114sr', 'text',              TRUE, 'stage_name_version',   NULL),
  (60748, 'Versão API',                'CustomColumn115sr', 'text',              TRUE,  'api_version',        NULL),
  (60748, 'Produto/Funcionalidade',    'CustomColumn165sr', 'text',              TRUE,  'product_feature',    NULL),
  (60748, 'Etapa(nome e versão api)',  'CustomColumn166sr', 'text',              TRUE,  'stage_name_version', NULL),
  (60749, 'Nome e Versão da API',     'CustomColumn114sr', 'text',              TRUE, 'stage_name_version',   NULL),
  (60749, 'Versão API',               'CustomColumn115sr', 'text',              TRUE,  'api_version',        NULL),
  (60749, 'Produto/Funcionalidade',   'CustomColumn165sr', 'text',              TRUE,  'product_feature',    NULL),
  (60749, 'Etapa(nome e versão api)', 'CustomColumn166sr', 'text',              TRUE,  'stage_name_version', NULL),
  (60749, 'Tipo do Cliente',          'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente',       '{"PF":"1","PJ":"2"}'),
  (60750, 'Destinatário',                          'CustomColumn38sr',  'text',              TRUE,  'destinatario',            NULL),
  (60750, 'URL do endpoint acionado',              'CustomColumn68sr',  'long',              TRUE,  'endpoint',                NULL),
  (60750, 'X-Fapi-Interaction-ID',                 'CustomColumn156sr', 'long',              TRUE,  'x_fapi_interaction_id',   NULL),
  (60750, 'ID do Consentimento',                   'CustomColumn157sr', 'long',              TRUE,  'id_consentimento',        NULL),
  (60750, 'Estado atual do consentimento',         'CustomColumn158sr', 'list',              TRUE,  'estado_consentimento',    NULL),
  (60750, 'O erro ocorre para um ou mais clientes?','CustomColumn159sr','text',              FALSE, 'erro_multiplos_clientes', NULL),
  (60750, 'Tipo do Cliente',                       'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente',            '{"PF":"1","PJ":"2"}'),
  (60750, 'Nome e Versão da API',                  'CustomColumn114sr', 'text',              TRUE, 'stage_name_version',        NULL),
  (60750, 'Versão API',                            'CustomColumn115sr', 'text',              TRUE,  'api_version',             NULL),
  (60750, 'Produto/Funcionalidade',                'CustomColumn165sr', 'text',              TRUE,  'product_feature',         NULL),
  (60750, 'Etapa(nome e versão api)',              'CustomColumn166sr', 'text',              TRUE,  'stage_name_version',      NULL),
  (60751, 'Destinatário',                           'CustomColumn38sr',  'text',              TRUE,  'destinatario',            NULL),
  (60751, 'URL do endpoint acionado',               'CustomColumn68sr',  'long',              TRUE,  'endpoint',                NULL),
  (60751, 'X-Fapi-Interaction-ID',                  'CustomColumn156sr', 'long',              TRUE,  'x_fapi_interaction_id',   NULL),
  (60751, 'ID do Pagamento',                        'CustomColumn160sr', 'long',              TRUE,  'id_pagamento',            NULL),
  (60751, 'Estado atual do pagamento',              'CustomColumn161sr', 'list',              TRUE,  'estado_pagamento',        NULL),
  (60751, 'O erro ocorre para um ou mais clientes?','CustomColumn159sr', 'text',              FALSE, 'erro_multiplos_clientes', NULL),
  (60751, 'Tipo do Cliente',                        'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente',            '{"PF":"1","PJ":"2"}'),
  (60751, 'Nome e Versão da API',                   'CustomColumn114sr', 'text',              TRUE, 'stage_name_version',        NULL),
  (60751, 'Versão API',                             'CustomColumn115sr', 'text',              TRUE,  'api_version',             NULL),
  (60751, 'Produto/Funcionalidade',                 'CustomColumn165sr', 'text',              TRUE,  'product_feature',         NULL),
  (60751, 'Etapa(nome e versão api)',               'CustomColumn166sr', 'text',              TRUE,  'stage_name_version',      NULL),
  (6752, 'Organisation ID',      'CustomColumn53sr', 'text', TRUE,  'organisation_id',      NULL),
  (6752, 'Software Statement ID','CustomColumn54sr', 'text', FALSE, 'software_statement_id', NULL),
  (68750, 'Destinatário',                                              'CustomColumn38sr',  'text',              TRUE, 'destinatario',       NULL),
  (68750, 'Este problema ocorreu no processo de Onboarding de ITP ?', 'CustomColumn59sr',  'text',              TRUE, 'onboarding_itp',     NULL),
  (68750, 'Nome e Versão da API',                                      'CustomColumn114sr', 'text',              TRUE, 'stage_name_version',   NULL),
  (68750, 'Versão API',                                                'CustomColumn115sr', 'text',              TRUE, 'api_version',        NULL),
  (68750, 'Produto/Funcionalidade',                                    'CustomColumn165sr', 'text',              TRUE, 'product_feature',    NULL),
  (68750, 'Etapa(nome e versão api)',                                  'CustomColumn166sr', 'text',              TRUE, 'stage_name_version', NULL),
  (68750, 'Tipo do Cliente',                                           'CustomColumn120sr', 'list_multi_select', TRUE, 'tipo_cliente',       '{"PF":"1","PJ":"2"}'),
  (68750, 'Canal da Jornada',                                          'CustomColumn174sr', 'list',              TRUE, 'canal_jornada',      '{"App to app":"1","App to browser":"2","Browser to browser":"3","Browser to app":"4","Não se aplica":"5"}'),
  (68751, 'Destinatário',                                  'CustomColumn38sr',  'text',              TRUE,  'destinatario',          NULL),
  (68751, 'Seu client_id nesta transmissora/detentora',    'CustomColumn79sr',  'text',              FALSE, 'client_id_transmissora', NULL),
  (68751, 'Nome e Versão da API',                          'CustomColumn114sr', 'text',              TRUE, 'stage_name_version',      NULL),
  (68751, 'Versão API',                                    'CustomColumn115sr', 'text',              TRUE,  'api_version',           NULL),
  (68751, 'Produto/Funcionalidade',                        'CustomColumn165sr', 'text',              TRUE,  'product_feature',       NULL),
  (68751, 'Etapa(nome e versão api)',                      'CustomColumn166sr', 'text',              TRUE,  'stage_name_version',    NULL),
  (68751, 'Tipo do Cliente',                               'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente',          '{"PF":"1","PJ":"2"}'),
  (68751, 'Canal da Jornada',                              'CustomColumn174sr', 'list',              FALSE, 'canal_jornada',         '{"App to app":"1","App to browser":"2","Browser to browser":"3","Browser to app":"4","Não se aplica":"5"}'),
  (68751, 'X-Fapi-Interaction-ID',                         'CustomColumn156sr', 'long',              FALSE, 'x_fapi_interaction_id', NULL),
  (68753, 'Destinatário',                                              'CustomColumn38sr',  'text',              TRUE,  'destinatario',        NULL),
  (68753, 'Nome da marca de destino',                                  'CustomColumn73sr',  'text',              TRUE,  'nome_marca_destino',  NULL),
  (68753, 'URL do arquivo .well-known da transmissora/detentora',      'CustomColumn74sr',  'long',              TRUE,  'url_well_known',      NULL),
  (68753, 'Conteúdo do arquivo .well-known da transmissora/detentora', 'CustomColumn75sr',  'long',              TRUE,  'conteudo_well_known', NULL),
  (68753, 'Tipo do Cliente',                                           'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente',        '{"PF":"1","PJ":"2"}'),
  (68753, 'Nome e Versão da API',                                      'CustomColumn114sr', 'text',              TRUE, 'stage_name_version',    NULL),
  (68753, 'Versão API',                                                'CustomColumn115sr', 'text',              TRUE,  'api_version',         NULL),
  (68753, 'Produto/Funcionalidade',                                    'CustomColumn165sr', 'text',              TRUE,  'product_feature',     NULL),
  (68753, 'Etapa(nome e versão api)',                                  'CustomColumn166sr', 'text',              TRUE,  'stage_name_version',  NULL),
  (68753, 'Canal da Jornada',                                          'CustomColumn174sr', 'list',              FALSE, 'canal_jornada',       '{"App to app":"1","App to browser":"2","Browser to browser":"3","Browser to app":"4","Não se aplica":"5"}'),
  (68753, 'X-Fapi-Interaction-ID',                                     'CustomColumn156sr', 'long',              FALSE, 'x_fapi_interaction_id', NULL),
  (789, 'Nome da instituição',    'CustomColumn9sr',  'text', TRUE,  'nome_instituicao',   NULL),
  (789, 'E-mail para notificação','CustomColumn12sr', 'text', FALSE, 'email_notificacao',  NULL),
  (789, 'E-mail do responsável',  'CustomColumn14sr', 'text', TRUE,  'email_responsavel',  NULL),
  (789, 'Fone para contato',      'CustomColumn8sr',  'text', TRUE,  'fone_contato',       NULL),
  (789, 'Analista, e-mail, fone', 'CustomColumn15sr', 'long', TRUE,  'analista_email_fone', NULL),
  (8794, 'Evidências do teste',    'CustomColumn84sr',  'text', FALSE, 'evidencias_teste',       NULL),
  (8794, 'Authorization Server ID','CustomColumn83sr',  'text', FALSE, 'authorization_server_id', NULL),
  (8794, 'Tipo de Erro',           'CustomColumn119sr', 'list', FALSE, 'tipo_erro',               NULL)
ON CONFLICT(template_id, field_name) DO UPDATE
SET
  field_label_api = EXCLUDED.field_label_api,
  field_type      = EXCLUDED.field_type,
  is_required     = EXCLUDED.is_required,
  context_key     = EXCLUDED.context_key,
  list_options    = EXCLUDED.list_options;
