INSERT INTO template_fields (
  template_id,
  field_name,
  field_label_api,
  field_type,
  is_required,
  context_key,
  list_options
) VALUES
  (20, 'Data Prevista para Implementação', 'CustomColumn82sr', 'datetime', TRUE, 'data_prevista_para_implementacao', NULL),
  (20, 'Justificativa Data Prevista', 'CustomColumn142sr', 'long', FALSE, 'justificativa_data_prevista', NULL),
  (20, 'Descrição', 'description', 'text', TRUE, 'descricao', NULL),
  (20, 'Título', 'title', 'text', TRUE, 'titulo', NULL),
  (68754, 'Data Prevista para Implementação', 'CustomColumn82sr', 'datetime', TRUE, 'data_prevista_para_implementacao', NULL),
  (68754, 'Justificativa Data Prevista', 'CustomColumn142sr', 'long', FALSE, 'justificativa_data_prevista', NULL),
  (68754, 'Tipo do Cliente', 'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente', '{"PF":"1","PJ":"2"}'),
  (68754, 'Descrição', 'description', 'text', TRUE, 'descricao', NULL),
  (68754, 'Título', 'title', 'text', TRUE, 'titulo', NULL),
  (68754, 'Canal da Jornada', 'CustomColumn174sr', 'list', FALSE, 'canal_jornada', '{"App to app":"1","App to browser":"2","Browser to browser":"3","Browser to app":"4","Não se aplica":"5"}'),
  (68754, 'URL do arquivo .well-known da transmissora/detentora', 'CustomColumn74sr', 'long', FALSE, 'url_well_known', NULL),
  (68754, 'Conteúdo do arquivo .well-known da transmissora/detentora', 'CustomColumn75sr', 'long', FALSE, 'conteudo_well_known', NULL),
  (68754, 'URL para qual o usuário deveria voltar', 'CustomColumn77sr', 'long', FALSE, 'url_retorno_usuario', NULL),
  (68754, 'SSA da sua aplicação', 'CustomColumn78sr', 'long', FALSE, 'ssa_aplicacao', NULL),
  (68754, 'X-Fapi-Interaction-ID', 'CustomColumn156sr', 'long', FALSE, 'x_fapi_interaction_id', NULL),
  (68760, 'Canal da Jornada', 'CustomColumn174sr', 'list', FALSE, 'canal_jornada', '{"App to app":"1","App to browser":"2","Browser to browser":"3","Browser to app":"4","Não se aplica":"5"}'),
  (68760, 'Indique a qual fase e etapa o problema está relacionado', 'CustomColumn93sr', 'list', FALSE, 'fase_etapa', NULL),
  (68760, 'Data Prevista para Implementação', 'CustomColumn82sr', 'datetime', TRUE, 'data_prevista_para_implementacao', NULL),
  (68760, 'Justificativa Data Prevista', 'CustomColumn142sr', 'long', FALSE, 'justificativa_data_prevista', NULL),
  (68760, 'Tipo do Cliente', 'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente', '{"PF":"1","PJ":"2"}'),
  (68760, 'Descrição', 'description', 'text', TRUE, 'descricao', NULL),
  (68760, 'Título', 'title', 'text', TRUE, 'titulo', NULL),
  (68760, 'X-Fapi-Interaction-ID', 'CustomColumn156sr', 'long', FALSE, 'x_fapi_interaction_id', NULL),
  (68762, 'Canal da Jornada', 'CustomColumn174sr', 'list', FALSE, 'canal_jornada', '{"App to app":"1","App to browser":"2","Browser to browser":"3","Browser to app":"4","Não se aplica":"5"}'),
  (68762, 'Data Prevista para Implementação', 'CustomColumn82sr', 'datetime', TRUE, 'data_prevista_para_implementacao', NULL),
  (68762, 'Justificativa Data Prevista', 'CustomColumn142sr', 'long', FALSE, 'justificativa_data_prevista', NULL),
  (68762, 'Tipo do Cliente', 'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente', '{"PF":"1","PJ":"2"}'),
  (68762, 'URL do endpoint acionado', 'CustomColumn68sr', 'long', FALSE, 'endpoint', NULL),
  (68762, 'Estado atual do consentimento', 'CustomColumn158sr', 'list', FALSE, 'estado_consentimento', NULL),
  (68762, 'Descrição', 'description', 'text', FALSE, 'descricao', NULL),
  (68762, 'Título', 'title', 'text', TRUE, 'titulo', NULL),
  (68762, 'ID do Consentimento', 'CustomColumn157sr', 'long', FALSE, 'id_consentimento', NULL),
  (68762, 'X-Fapi-Interaction-ID', 'CustomColumn156sr', 'long', FALSE, 'x_fapi_interaction_id', NULL),
  (68763, 'Canal da Jornada', 'CustomColumn174sr', 'list', FALSE, 'canal_jornada', '{"App to app":"1","App to browser":"2","Browser to browser":"3","Browser to app":"4","Não se aplica":"5"}'),
  (68763, 'Data Prevista para Implementação', 'CustomColumn82sr', 'datetime', TRUE, 'data_prevista_para_implementacao', NULL),
  (68763, 'Estado atual do pagamento', 'CustomColumn161sr', 'list', FALSE, 'estado_pagamento', NULL),
  (68763, 'Justificativa Data Prevista', 'CustomColumn142sr', 'long', FALSE, 'justificativa_data_prevista', NULL),
  (68763, 'Tipo do Cliente', 'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente', '{"PF":"1","PJ":"2"}'),
  (68763, 'ID do Pagamento', 'CustomColumn160sr', 'long', FALSE, 'id_pagamento', NULL),
  (68763, 'URL do endpoint acionado', 'CustomColumn68sr', 'long', FALSE, 'endpoint', NULL),
  (68763, 'Descrição', 'description', 'text', FALSE, 'descricao', NULL),
  (68763, 'Título', 'title', 'text', TRUE, 'titulo', NULL),
  (68763, 'X-Fapi-Interaction-ID', 'CustomColumn156sr', 'long', FALSE, 'x_fapi_interaction_id', NULL),
  (83331, 'Data Prevista para Implementação', 'CustomColumn82sr', 'datetime', TRUE, 'data_prevista_para_implementacao', NULL),
  (83331, 'Descrição', 'description', 'text', TRUE, 'descricao', NULL),
  (83331, 'Título', 'title', 'text', TRUE, 'titulo', NULL),
  (83331, 'Segmento executado', 'CustomColumn178sr', 'list', FALSE, 'segmento_executado', NULL),
  (83331, 'Sistema Operacional', 'CustomColumn179sr', 'list', FALSE, 'sistema_operacional', NULL),
  (83331, 'Forma de execução', 'CustomColumn177sr', 'list', FALSE, 'forma_de_execucao', NULL),
  (83331, 'Módulo do teste executado', 'CustomColumn210sr', 'long', FALSE, 'modulo_do_teste_executado', NULL),
  (83830, 'Data Prevista para Implementação', 'CustomColumn82sr', 'datetime', TRUE, 'data_prevista_para_implementacao', NULL),
  (83830, 'Justificativa Data Prevista', 'CustomColumn142sr', 'long', FALSE, 'justificativa_data_prevista', NULL),
  (83830, 'Descrição', 'description', 'text', TRUE, 'descricao', NULL),
  (83830, 'Título', 'title', 'text', TRUE, 'titulo', NULL),
  (123327, 'Data Prevista para Implementação', 'CustomColumn82sr', 'datetime', TRUE, 'data_prevista_para_implementacao', NULL),
  (123327, 'Justificativa Data Prevista', 'CustomColumn142sr', 'long', FALSE, 'justificativa_data_prevista', NULL),
  (123327, 'Tipo do Cliente', 'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente', '{"PF":"1","PJ":"2"}'),
  (123327, 'Código HTTP da resposta', 'CustomColumn229sr', 'list', FALSE, 'http_status_code', '{"429":"2","5xx":"4","4xx":"3","*":"1"}'),
  (123327, 'URL do endpoint acionado', 'CustomColumn68sr', 'long', FALSE, 'endpoint', NULL),
  (123327, 'Headers e Payload da solicitação (Request)', 'CustomColumn69sr', 'long', FALSE, 'payload_request', NULL),
  (123327, 'Descrição', 'description', 'text', TRUE, 'descricao', NULL),
  (123327, 'Título', 'title', 'text', TRUE, 'titulo', NULL),
  (123327, 'Canal da Jornada', 'CustomColumn174sr', 'list', FALSE, 'canal_jornada', '{"App to app":"1","App to browser":"2","Browser to browser":"3","Browser to app":"4","Não se aplica":"5"}'),
  (123327, 'Headers e Payload da resposta (Response)', 'CustomColumn71sr', 'long', FALSE, 'payload_response', NULL),
  (123327, 'X-Fapi-Interaction-ID', 'CustomColumn156sr', 'long', FALSE, 'x_fapi_interaction_id', NULL),
  (123330, 'Data Prevista para Implementação', 'CustomColumn82sr', 'datetime', TRUE, 'data_prevista_para_implementacao', NULL),
  (123330, 'Justificativa Data Prevista', 'CustomColumn142sr', 'long', FALSE, 'justificativa_data_prevista', NULL),
  (123330, 'Tipo do Cliente', 'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente', '{"PF":"1","PJ":"2"}'),
  (123330, 'Código HTTP da resposta', 'CustomColumn229sr', 'list', FALSE, 'http_status_code', '{"429":"2","5xx":"4","4xx":"3","*":"1"}'),
  (123330, 'URL do endpoint acionado', 'CustomColumn68sr', 'long', FALSE, 'endpoint', NULL),
  (123330, 'Headers e Payload da solicitação (Request)', 'CustomColumn69sr', 'long', FALSE, 'payload_request', NULL),
  (123330, 'Descrição', 'description', 'text', TRUE, 'descricao', NULL),
  (123330, 'Título', 'title', 'text', TRUE, 'titulo', NULL),
  (123330, 'Canal da Jornada', 'CustomColumn174sr', 'list', FALSE, 'canal_jornada', '{"App to app":"1","App to browser":"2","Browser to browser":"3","Browser to app":"4","Não se aplica":"5"}'),
  (123330, 'Headers e Payload da resposta (Response)', 'CustomColumn71sr', 'long', FALSE, 'payload_response', NULL),
  (123330, 'URL do arquivo .well-known da transmissora/detentora', 'CustomColumn74sr', 'long', FALSE, 'url_well_known', NULL),
  (123330, 'Conteúdo do arquivo .well-known da transmissora/detentora', 'CustomColumn75sr', 'long', FALSE, 'conteudo_well_known', NULL),
  (123330, 'X-Fapi-Interaction-ID', 'CustomColumn156sr', 'long', FALSE, 'x_fapi_interaction_id', NULL),
  (123331, 'Data Prevista para Implementação', 'CustomColumn82sr', 'datetime', TRUE, 'data_prevista_para_implementacao', NULL),
  (123331, 'Justificativa Data Prevista', 'CustomColumn142sr', 'long', FALSE, 'justificativa_data_prevista', NULL),
  (123331, 'Tipo do Cliente', 'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente', '{"PF":"1","PJ":"2"}'),
  (123331, 'Código HTTP da resposta', 'CustomColumn229sr', 'list', FALSE, 'http_status_code', '{"429":"2","5xx":"4","4xx":"3","*":"1"}'),
  (123331, 'URL do endpoint acionado', 'CustomColumn68sr', 'long', FALSE, 'endpoint', NULL),
  (123331, 'Headers e Payload da solicitação (Request)', 'CustomColumn69sr', 'long', FALSE, 'payload_request', NULL),
  (123331, 'Descrição', 'description', 'text', TRUE, 'descricao', NULL),
  (123331, 'Título', 'title', 'text', TRUE, 'titulo', NULL),
  (123331, 'Canal da Jornada', 'CustomColumn174sr', 'list', FALSE, 'canal_jornada', '{"App to app":"1","App to browser":"2","Browser to browser":"3","Browser to app":"4","Não se aplica":"5"}'),
  (123331, 'Headers e Payload da resposta (Response)', 'CustomColumn71sr', 'long', FALSE, 'payload_response', NULL),
  (123331, 'X-Fapi-Interaction-ID', 'CustomColumn156sr', 'long', FALSE, 'x_fapi_interaction_id', NULL),
  (123333, 'Canal da Jornada', 'CustomColumn174sr', 'list', FALSE, 'canal_jornada', '{"App to app":"1","App to browser":"2","Browser to browser":"3","Browser to app":"4","Não se aplica":"5"}'),
  (123333, 'Data Prevista para Implementação', 'CustomColumn82sr', 'datetime', TRUE, 'data_prevista_para_implementacao', NULL),
  (123333, 'Justificativa Data Prevista', 'CustomColumn142sr', 'long', FALSE, 'justificativa_data_prevista', NULL),
  (123333, 'Tipo do Cliente', 'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente', '{"PF":"1","PJ":"2"}'),
  (123333, 'Código HTTP da resposta', 'CustomColumn229sr', 'list', FALSE, 'http_status_code', '{"429":"2","5xx":"4","4xx":"3","*":"1"}'),
  (123333, 'URL do endpoint acionado', 'CustomColumn68sr', 'long', FALSE, 'endpoint', NULL),
  (123333, 'Descrição', 'description', 'text', TRUE, 'descricao', NULL),
  (123333, 'Título', 'title', 'text', TRUE, 'titulo', NULL),
  (123333, 'X-Fapi-Interaction-ID', 'CustomColumn156sr', 'long', FALSE, 'x_fapi_interaction_id', NULL),
  (164790, 'Canal da Jornada', 'CustomColumn174sr', 'list', FALSE, 'canal_jornada', '{"App to app":"1","App to browser":"2","Browser to browser":"3","Browser to app":"4","Não se aplica":"5"}'),
  (164790, 'Headers e Payload da resposta (Response)', 'CustomColumn71sr', 'long', FALSE, 'payload_response', NULL),
  (164790, 'Data Prevista para Implementação', 'CustomColumn82sr', 'datetime', TRUE, 'data_prevista_para_implementacao', NULL),
  (164790, 'Justificativa Data Prevista', 'CustomColumn142sr', 'long', FALSE, 'justificativa_data_prevista', NULL),
  (164790, 'Tipo do Cliente', 'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente', '{"PF":"1","PJ":"2"}'),
  (164790, 'Código HTTP da resposta', 'CustomColumn229sr', 'list', FALSE, 'http_status_code', '{"429":"2","5xx":"4","4xx":"3","*":"1"}'),
  (164790, 'URL do endpoint acionado', 'CustomColumn68sr', 'long', FALSE, 'endpoint', NULL),
  (164790, 'Headers e Payload da solicitação (Request)', 'CustomColumn69sr', 'long', FALSE, 'payload_request', NULL),
  (164790, 'Descrição', 'description', 'text', TRUE, 'descricao', NULL),
  (164790, 'Título', 'title', 'text', TRUE, 'titulo', NULL),
  (164790, 'X-Fapi-Interaction-ID', 'CustomColumn156sr', 'long', FALSE, 'x_fapi_interaction_id', NULL),
  (164792, 'Data Prevista para Implementação', 'CustomColumn82sr', 'datetime', TRUE, 'data_prevista_para_implementacao', NULL),
  (164792, 'Justificativa Data Prevista', 'CustomColumn142sr', 'long', FALSE, 'justificativa_data_prevista', NULL),
  (164792, 'Tipo do Cliente', 'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente', '{"PF":"1","PJ":"2"}'),
  (164792, 'Código HTTP da resposta', 'CustomColumn229sr', 'list', FALSE, 'http_status_code', '{"429":"2","5xx":"4","4xx":"3","*":"1"}'),
  (164792, 'URL do endpoint acionado', 'CustomColumn68sr', 'long', FALSE, 'endpoint', NULL),
  (164792, 'Headers e Payload da solicitação (Request)', 'CustomColumn69sr', 'long', FALSE, 'payload_request', NULL),
  (164792, 'Descrição', 'description', 'text', TRUE, 'descricao', NULL),
  (164792, 'Título', 'title', 'text', TRUE, 'titulo', NULL),
  (164792, 'Canal da Jornada', 'CustomColumn174sr', 'list', FALSE, 'canal_jornada', '{"App to app":"1","App to browser":"2","Browser to browser":"3","Browser to app":"4","Não se aplica":"5"}'),
  (164792, 'Headers e Payload da resposta (Response)', 'CustomColumn71sr', 'long', FALSE, 'payload_response', NULL),
  (164792, 'X-Fapi-Interaction-ID', 'CustomColumn156sr', 'long', FALSE, 'x_fapi_interaction_id', NULL),
  (164793, 'Canal da Jornada', 'CustomColumn174sr', 'list', FALSE, 'canal_jornada', '{"App to app":"1","App to browser":"2","Browser to browser":"3","Browser to app":"4","Não se aplica":"5"}'),
  (164793, 'Data Prevista para Implementação', 'CustomColumn82sr', 'datetime', TRUE, 'data_prevista_para_implementacao', NULL),
  (164793, 'Justificativa Data Prevista', 'CustomColumn142sr', 'long', FALSE, 'justificativa_data_prevista', NULL),
  (164793, 'Tipo do Cliente', 'CustomColumn120sr', 'list_multi_select', FALSE, 'tipo_cliente', '{"PF":"1","PJ":"2"}'),
  (164793, 'Descrição', 'description', 'text', TRUE, 'descricao', NULL),
  (164793, 'Título', 'title', 'text', TRUE, 'titulo', NULL),
  (164793, 'X-Fapi-Interaction-ID', 'CustomColumn156sr', 'long', FALSE, 'x_fapi_interaction_id', NULL)
ON CONFLICT(template_id, field_name) DO UPDATE
SET
  field_label_api = EXCLUDED.field_label_api,
  field_type      = EXCLUDED.field_type,
  is_required     = EXCLUDED.is_required,
  context_key     = EXCLUDED.context_key,
  list_options    = EXCLUDED.list_options;